package ch.admin.bit.jeap.jme.doc;

import ch.admin.bit.jeap.jme.test.BootServiceSpringIntegrationTestBase;
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Frame;
import com.microsoft.playwright.Keyboard;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.TimeoutError;
import com.microsoft.playwright.assertions.PlaywrightAssertions;
import com.microsoft.playwright.options.AriaRole;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Value;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectTaggingRequest;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
import software.amazon.awssdk.services.s3.model.S3Object;
import software.amazon.awssdk.services.s3.model.Tag;

import java.net.URI;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.Matchers.contains;
import static org.hamcrest.Matchers.containsInAnyOrder;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.empty;
import static org.hamcrest.Matchers.endsWith;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.nullValue;

/**
 * Generates the documentation site of this example out of a stubbed architecture model, and reads what the
 * generator did - over the API and, where only a browser can tell, in a browser.
 * <p>
 * This is the half of the doc service that publishes rather than receives, and it is what makes the example
 * need Node and a Chrome: the site is generated by running the site generator as a child process. So this is
 * the suite that fails when the local development environment is not set up - if the doc service never becomes
 * ready here, its {@code jeap.doc.build.*} configuration is where to look, and {@code docs/local-development.md}
 * says what it has to point at.
 * <p>
 * <b>The whole chain, in the order a landscape travels it</b>: an operator asks for the upstreams to be
 * imported, the import stores what they answer and asks for every part of the site, the parts are generated
 * and published, and the pages are then read by a browser that never authenticated itself. Both upstreams are
 * the stub of this example rather than an architecture repository and a reaction observer - see the
 * {@code jme-doc-upstream-stub} module for what it holds and why it exists.
 * <p>
 * <b>Two upstreams, and the second one is what the runtime views are drawn from</b>: the reactions are steps
 * of the same import, they run after the model because every observed name is resolved against it, and the
 * documentation of an environment is asked for once its whole chain has run. Every environment of this site
 * reads both, so every tree of it carries the landscape and its runtime views.
 * <p>
 * <b>A site is published as one build per part</b>: the <i>shell</i>, which carries the site's own pages and
 * everything no system claims, plus one part per system of the model. The stubbed landscape has two systems,
 * so this site has three parts - and they are built one after another, because
 * {@code jeap.doc.build.max-concurrent-parts} is 1 in this instance.
 * <p>
 * <b>Both halves of the hybrid model end up on it</b>: what the generator writes out of the model, and what a
 * team uploads next to its code. The upload is driven here rather than in the API suite because this is where a
 * build can be waited for - the example publishes the stubbed landscape alone, so one is quick - and seeing the
 * page served is the only thing that says an upload was published rather than only stored.
 * <p>
 * <b>Administering a site is not a system's own business.</b> The upload roles carry the system in their tenant
 * part so that a pipeline can only change its own documentation, while a build regenerates a part with the
 * documentation of every repository in it - so it is granted on a resource of its own that no pipeline holds.
 * <p>
 * The tests are ordered because they are one story. That several triggers collapse into a single build is not
 * asserted here - that is the doc service's own behaviour and is covered there. This suite is about the
 * instance being wired up correctly.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DocSiteExampleIT extends BootServiceSpringIntegrationTestBase {

    private static final List<Integer> SERVICE_PORTS = reserveFreePorts(3);
    private static final int AUTH_PORT = SERVICE_PORTS.getFirst();
    private static final int STUB_PORT = SERVICE_PORTS.get(1);
    private static final int DOC_PORT = SERVICE_PORTS.get(2);
    private static final String AUTH_BASE_URL = "http://localhost:" + AUTH_PORT + "/jme-doc-auth-scs";
    private static final String STUB_BASE_URL = "http://localhost:" + STUB_PORT + "/jme-doc-upstream-stub";
    private static final String DOC_BASE_URL = "http://localhost:" + DOC_PORT + "/jme-doc-service";

    /**
     * The default site. It is served at the context root, and it is the site an upload that names none belongs
     * to.
     */
    private static final String SITE = "default";

    /**
     * The second site, which needs no architecture model: its one environment has no architecture repository,
     * so nothing but an upload and an operator publishes it. It is served below {@code /site/handbook/}, and its
     * one environment is its main one, so that is also the root of its only tree.
     */
    private static final String HANDBOOK = DocumentationSets.HANDBOOK_SITE;
    private static final String HANDBOOK_ROOT = "/site/" + HANDBOOK + "/";
    private static final String HANDBOOK_SITE_PATH = "/api/sites/" + HANDBOOK;
    private static final String HANDBOOK_TITLE = "JME Handbook";
    private static final String HANDBOOK_TAGLINE = "How the JME team works";

    /** The primary colour of the {@code neutral} scheme the handbook is configured with. */
    private static final String NEUTRAL_PRIMARY_COLOUR = "#414c57";

    /** A site nobody configures - a typo, as far as the instance can tell. */
    private static final String UNCONFIGURED_SITE = "governance";

    /**
     * The environments of the site. All four read an architecture model here, and all four read the same one:
     * the site has one upstream behind it, so every tree of it carries the stubbed landscape and the
     * environment switcher leads somewhere. {@code prod} is the main environment and is served at the root.
     */
    private static final List<String> ENVIRONMENTS = List.of("dev", "ref", "abn", "prod");

    /**
     * The main environment. It is served at the site root and has <b>no path of its own</b>, so it is the one
     * environment the trees below are not read under {@code /<environment>/}.
     */
    private static final String MAIN_ENVIRONMENT = "prod";

    /** One of the others, the one whose tree is read below - any of them would do, they carry the same model. */
    private static final String ENVIRONMENT = "dev";

    /**
     * The part that carries the site's own pages - its root page, the systems index, the page about the
     * documentation - and everything no other part claims. It is the one part every site has, whatever the
     * architecture model holds.
     */
    private static final String SHELL_PART = "shell";

    /** The parts the two systems of the stubbed landscape are published as. */
    private static final String JME_PART = "system-jme";
    private static final String ORDERS_PART = "system-orders";

    private static final String SITE_PATH = "/api/sites/" + SITE;
    private static final String BUILDS_PATH = SITE_PATH + "/builds";
    private static final String PARTS_PATH = SITE_PATH + "/parts";
    private static final String SHELL_BUILDS_PATH = PARTS_PATH + "/" + SHELL_PART + "/builds";
    private static final String IMPORTS_PATH = "/api/architecture/imports";
    private static final String IMPORT_STATE_PATH = "/api/architecture/environments";
    private static final String UPLOAD_PATH = "/api/uploads/docs/";
    private static final String REMOVE_SETS_PATH = "/api/docs/custom/sets";

    /** The tree of the system the uploads of this suite document, below the tree of an environment. */
    private static final String SYSTEM_TREE = "/systems/" + DocumentationSets.SYSTEM + "/system-architecture/";

    /** The three steps that read the reaction observer rather than the architecture repository. */
    private static final List<String> REACTION_KINDS =
            List.of("SYSTEM_REACTIONS", "COMPONENT_REACTIONS", "MESSAGE_REACTIONS");

    /** What the search downloads: one index over the whole site, published beside the parts it covers. */
    private static final String SEARCH_INDEX = "/pagefind/pagefind.js";

    /**
     * Where the generator writes the context view of a system: below the system, the arc42 structure, the
     * chapter without its number, and the page.
     */
    private static final String SYSTEM_CONTEXT_VIEW =
            "/systems/jme/system-architecture/context-and-scope/system-context-view/";

    /**
     * What the stubbed reaction observer says was seen happening: the doc service reacting to the event of
     * the other system. Both are in the architecture model too, and they have to be - a name the model does
     * not hold is not imported, so a reaction naming one would document nothing.
     */
    private static final String REACTING_COMPONENT = "jme-doc-service";
    private static final String REACTING_MESSAGE = "OrdersPaymentAcceptedEvent";

    /**
     * Where the generator writes a runtime view: chapter 6 of the system, and chapter 6 of the component
     * inside the chapter that decomposes the system into its components.
     */
    private static final String SYSTEM_REACTIONS =
            "/systems/jme/system-architecture/runtime-view/system-reactions/";
    private static final String COMPONENT_REACTIONS =
            "/systems/jme/system-architecture/building-block-view/components/" + REACTING_COMPONENT
            + "/component-architecture/runtime-view/component-reactions/";

    /**
     * The URL segment of the chapter the uploaded page is filed in - {@code 1-intro} without its number. The
     * number is part of arc42 and belongs in the folder, not in a link.
     */
    private static final String UPLOADED_CHAPTER_SEGMENT = "intro";

    /** The picture of the uploaded page as the site renders it, found by what the page calls it. */
    private static final Pattern UPLOADED_PICTURE =
            Pattern.compile("<img[^>]*alt=\"" + Pattern.quote(DocumentationSets.IMAGE_ALT) + "\"[^>]*>");
    /** Quoted or not: the published HTML is minified, and a value without spaces loses its quotes. */
    private static final Pattern SOURCE = Pattern.compile("\\ssrc=(?:\"([^\"]+)\"|([^\\s\"'>]+))");

    /** What the site of this example calls itself - configured in the instance, and read back off the page. */
    private static final String SITE_TITLE = "JME Documentation";

    /**
     * How often the instance under test looks whether a build has been asked for. Far below the 30 seconds of
     * a real instance, because every test here waits for a build: it is the one number that decides how long
     * this suite takes, and the endpoints answer it as {@code picksUpWithinSeconds}, which is asserted below.
     */
    private static final int POLL_INTERVAL_SECONDS = 2;

    /**
     * How long the parts may take before the suite gives up on them. Generously above the twenty to thirty
     * seconds each site generator run needs, because they run one after another and the first one on a cold
     * machine has a bundler to warm up.
     */
    private static final Duration BUILD_TIMEOUT = Duration.ofMinutes(10);

    /**
     * The tag every file of a generated site carries - see docker/docker-compose.yml. The bundle of an upload
     * carries the same key with the value {@code upload}, which is what lets the lifecycle rule of the bucket
     * expire the bundles without touching the sites.
     */
    private static final String SITE_TAG_KEY = "jeap-doc-content";
    private static final String SITE_TAG_VALUE = "site";

    /** The shell's publication, so that everything read afterwards is read about that build and no other. */
    private static long publishedBuildId;

    private static Playwright playwright;
    private static Browser browser;

    @Value("${jme-doc-test.objectstorage.endpoint-url}")
    private URI objectStorageEndpoint;
    @Value("${jme-doc-test.objectstorage.region}")
    private String objectStorageRegion;
    @Value("${jme-doc-test.objectstorage.access-key}")
    private String objectStorageAccessKey;
    @Value("${jme-doc-test.objectstorage.secret-key}")
    private String objectStorageSecretKey;
    @Value("${jme-doc-test.objectstorage.bucket}")
    private String documentationBucket;

    /**
     * Three services: the OAuth mock server issuing every token, the upstream stub holding the architecture
     * model, and the doc service.
     * <p>
     * Four settings of the doc service are the suite's rather than the instance's, and each one is here to
     * make an outcome of this suite the outcome of something it did:
     * <ul>
     *   <li>where the upstream stub is - for every environment, because all four read it - since it runs on a
     *       free port here rather than on the 8082 the instance configures;
     *   <li>no import on startup and no import schedule, so the only import that happens is the one this
     *       suite asks for - which is what lets it show the site before the model and after it;
     *   <li>the poll interval, so a build starts seconds after it is asked for instead of within half a
     *       minute;
     *   <li>the publication URL, which names the origin in the metadata of the generated pages.
     * </ul>
     * The reconcile schedule is switched off for the same reason as the import: it is what publishes a site no
     * architecture import feeds, and an unasked-for build in the middle of this suite would be a second
     * explanation for everything it observes.
     */
    @BeforeAll
    static void startServices() throws Exception {
        startService("jme-doc-auth-scs", AUTH_BASE_URL, Map.of(
                "server.port", String.valueOf(AUTH_PORT),
                "mockserver.base-url", AUTH_BASE_URL));
        startService("jme-doc-upstream-stub", STUB_BASE_URL, Map.of(
                "server.port", String.valueOf(STUB_PORT),
                "jeap.security.oauth2.resourceserver.authorization-server.issuer", AUTH_BASE_URL,
                "jeap.security.oauth2.resourceserver.authorization-server.jwk-set-uri",
                AUTH_BASE_URL + "/.well-known/jwks.json"));
        Map<String, String> docService = new LinkedHashMap<>(Map.of(
                "server.port", String.valueOf(DOC_PORT),
                "jeap.security.oauth2.resourceserver.authorization-server.issuer", AUTH_BASE_URL,
                "jeap.security.oauth2.resourceserver.authorization-server.jwk-set-uri",
                AUTH_BASE_URL + "/.well-known/jwks.json",
                "spring.security.oauth2.client.provider.archrepo.token-uri", AUTH_BASE_URL + "/oauth2/token",
                "spring.security.oauth2.client.provider.reactions.token-uri", AUTH_BASE_URL + "/oauth2/token",
                "jeap.doc.archrepo.import.on-startup", "false",
                "jeap.doc.archrepo.import.cron", "",
                "jeap.doc.build.poll-interval", "PT" + POLL_INTERVAL_SECONDS + "S",
                "jeap.doc.build.reconcile-cron", "-",
                "jeap.doc.publication.url", "http://localhost:" + DOC_PORT));
        ENVIRONMENTS.forEach(environment -> {
            docService.put("jeap.doc.archrepo.environments." + environment + ".url", STUB_BASE_URL);
            docService.put("jeap.doc.reactions.environments." + environment + ".url", STUB_BASE_URL);
        });
        startService("jme-doc-service", DOC_BASE_URL, docService);
    }

    /**
     * The browser comes from the machine, as Node and Docker do: the channel takes the installed Chrome, and
     * the driver is told not to fetch its own bundles - hundreds of megabytes on every fresh CI container, and
     * a hard failure where the network does not allow it. A suite that skipped itself where no browser is
     * present would be green because it ran nothing.
     */
    @BeforeAll
    static void startBrowser() {
        playwright = Playwright.create(new Playwright.CreateOptions()
                .setEnv(Map.of("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1")));
        browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setChannel("chrome"));
        PlaywrightAssertions.setDefaultAssertionTimeout(15_000);
    }

    @AfterAll
    static void stopBrowser() {
        if (browser != null) {
            browser.close();
        }
        if (playwright != null) {
            playwright.close();
        }
    }

    /**
     * Where the model of each environment is read from, as an operator asks it. Every environment of this
     * example reads the one upstream stub - a real instance names the architecture repository of the stage
     * here, and those are four different services.
     */
    @Test
    @Order(1)
    void theImportStateSaysWhereTheModelComesFrom() {
        JsonPath imports = readJson(IMPORT_STATE_PATH);

        assertThat(imports.getList("environment", String.class))
                .containsExactlyInAnyOrderElementsOf(ENVIRONMENTS);
        assertThat(imports.getList("sourceUrl", String.class)).containsOnly(STUB_BASE_URL);
        assertThat(imports.getList("[0].imports.kind", String.class)).contains("MODEL");
    }

    /**
     * The import fetches the landscape whole and, when it is not the one already stored, replaces it whole.
     * Nothing runs on the request: the ask is put on this instance's import queue and answered {@code 202},
     * and it is deliberately not durable - which is why what became of it is polled rather than assumed.
     * <p>
     * <b>The import is also the trigger</b>: what it stores is documentation that is out of date, so it asks
     * for every part of the site itself rather than leaving that to a schedule. What the site is cut into is
     * what this asserts - the shell it always had, and one part per system the model brought.
     */
    @Test
    @Order(2)
    void askingForTheModelImportsItAndPublishesEveryPart() {
        List<String> before = importedAt();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(IMPORTS_PATH)
                .then()
                .statusCode(202)
                .body("environments", containsInAnyOrder(ENVIRONMENTS.toArray()))
                .body("refused", empty())
                .body("durable", equalTo(false));

        // Every environment, not the first one to arrive: the imports run one after another on one thread,
        // and a site whose trees are generated from half an import would be a site read too early.
        await().atMost(Duration.ofMinutes(4))
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> {
                    List<String> now = importedAt();
                    return !now.contains(null) && !now.equals(before);
                });

        assertThat(readJson(PARTS_PATH).getList("part", String.class))
                .containsExactlyInAnyOrder(SHELL_PART, JME_PART, ORDERS_PART);

        // Every part published and none of them owed a build, rather than a count of builds of one trigger: a
        // request that is already pending keeps the trigger that asked first, so which trigger a part ends up
        // being built by is not something a caller decides.
        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(2))
                .until(this::everyPartIsPublished);
        publishedBuildId = publishedBuildIdOf(SHELL_PART);
    }

    /**
     * What the site is published as, and the answer to <i>is this documentation up to date</i> now that no
     * single build is the site: per part what it carries, what is published for it, how old that is and
     * whether a build of it is owed.
     */
    @Test
    @Order(3)
    void thePartsSayWhatEachOfThemCarries() {
        JsonPath parts = readJson(PARTS_PATH);

        assertThat(parts.getList("findAll { it.owedABuild }.part", String.class)).isEmpty();
        assertThat(parts.getList("contentDigest", String.class)).doesNotContainNull();
        assertThat(parts.getString("find { it.part == '%s' }.documents".formatted(SHELL_PART)))
                .isEqualTo("the site itself");
        assertThat(parts.getString("find { it.part == '%s' }.documents".formatted(JME_PART)))
                .isEqualTo("the system jme");
        // The shell owns no subtree of its own: it answers for whatever no other part claims.
        assertThat(parts.getList("find { it.part == '%s' }.routePrefixes".formatted(SHELL_PART), String.class))
                .isEmpty();
        assertThat(parts.getList("find { it.part == '%s' }.routePrefixes".formatted(JME_PART), String.class))
                .contains("/" + ENVIRONMENT + "/systems/jme/");
    }

    /**
     * The documentation is served to anyone who can reach the service, and the API is not - which is the whole
     * of that decision, seen from outside. What the page says comes from the instance: the title is the one
     * configured in its application.yml, and the root of the site is its main environment.
     */
    @Test
    @Order(4)
    void theSiteIsServedToAnyoneWithoutAToken() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/")
                .then()
                .statusCode(200)
                .body(containsString(SITE_TITLE))
                .body(containsString("Production"));
    }

    /**
     * Every environment of the site is a tree of its own below it, and the main one is additionally served at
     * the root. The site is generated with a trailing slash on every route, so the form without one is a
     * redirect rather than a second URL for the same page.
     */
    @Test
    @Order(5)
    void everyEnvironmentIsServedUnderItsOwnPath() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/" + ENVIRONMENT + "/")
                .then()
                .statusCode(200)
                .body(containsString("Development"));

        given().baseUri(DOC_BASE_URL)
                .redirects().follow(false)
                .when()
                .get("/" + ENVIRONMENT)
                .then()
                .statusCode(301)
                .header("Location", endsWith("/" + ENVIRONMENT + "/"));
    }

    /**
     * A page out of the part that carries a system, which is the whole point of importing a model: the tree of
     * that system is generated and served under the route of every environment - the main one at the root
     * included, which is what a reader who follows a bare link to this instance gets.
     */
    @Test
    @Order(6)
    void theDocumentationGeneratedFromTheModelIsServed() {
        for (String environment : ENVIRONMENTS) {
            // The main environment is served at the root and nowhere else, which is where its tree is read.
            String tree = environment.equals(MAIN_ENVIRONMENT) ? "" : "/" + environment;

            given().baseUri(DOC_BASE_URL)
                    .when()
                    .get(tree + "/systems/jme/")
                    .then()
                    .statusCode(200);

            given().baseUri(DOC_BASE_URL)
                    .when()
                    .get(tree + "/systems/orders/")
                    .then()
                    .statusCode(200);
        }
    }

    /**
     * The reactions, which are the <b>second upstream</b> of a documentation site: the reaction observer of
     * the environment, read as steps of the same import and drawn as the runtime views of a system, a
     * component and a message.
     * <p>
     * The stub answers for the observer as well as for the architecture repository, so what this asserts is
     * the whole of that integration in this instance: a second client registration, a second role, the three
     * replication indexes, and the pages the graphs end up on.
     */
    @Test
    @Order(7)
    void theReactionsObservedAtRuntimeAreImported() {
        JsonPath imports = readJson(IMPORT_STATE_PATH);

        for (String kind : REACTION_KINDS) {
            String step = "find { it.environment == '%s' }.imports.find { it.kind == '%s' }"
                    .formatted(ENVIRONMENT, kind);
            assertThat(imports.getString(step + ".lastSuccessAt"))
                    .as("the %s of %s were imported", kind, ENVIRONMENT)
                    .isNotNull();
            assertThat(imports.getInt(step + ".itemCount"))
                    .as("graphs of %s stored for %s", kind, ENVIRONMENT)
                    .isPositive();
            assertThat(imports.getString(step + ".failureReason")).isNull();
        }
    }

    /**
     * Where a reaction ends up on the site. Chapter 6 of a system and of a component, and - for a message -
     * a section of the message's own page, so that a reader who has the message in front of them sees what
     * answers it without leaving the page.
     * <p>
     * <b>What is asserted is the content and not only the status.</b> A page of a runtime view carries the
     * graph as a source block and the same reactions as a table, and it is the table that survives whatever
     * the browser does with the source - so the names have to be in the answer.
     */
    @Test
    @Order(8)
    void theRuntimeViewsOfTheReactionsAreServed() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/" + ENVIRONMENT + SYSTEM_REACTIONS)
                .then()
                .statusCode(200)
                // The message the doc service was observed reacting to, and the component that reacted.
                .body(containsString(REACTING_MESSAGE))
                .body(containsString(REACTING_COMPONENT));

        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/" + ENVIRONMENT + COMPONENT_REACTIONS)
                .then()
                .statusCode(200)
                .body(containsString(REACTING_MESSAGE));

        // The system whose component published that message reacts too, and to the other message type - the
        // chain the reactions of the stubbed landscape are: an order is placed, the payment system reacts and
        // publishes what became of the payment, the doc service reacts to that.
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/" + ENVIRONMENT + "/systems/orders/system-architecture/runtime-view/system-reactions/")
                .then()
                .statusCode(200)
                .body(containsString("OrdersOrderPlacedEvent"))
                .body(containsString("orders-payment-scs"));
    }

    /**
     * The site brings its own not-found page, and it is served with the status that says so - a reader gets
     * the navigation of the documentation they were looking for rather than an error page of the service.
     */
    @Test
    @Order(9)
    void anUnknownPageIsAnsweredWithTheSitesOwnNotFoundPage() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/nothing-was-published-here/")
                .then()
                .statusCode(404)
                .body(containsString("Page Not Found"));
    }

    /**
     * The systems the model contributed, as a reader reaches them: from the index of the shell's build into a
     * tree that another build produced. It is the one assertion that the parts really are one site - the link
     * is written by a build that cannot see the pages it points at.
     */
    @Test
    @Order(10)
    void theSystemsOfTheModelAreReachableFromTheIndex() {
        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, "/" + ENVIRONMENT + "/");

            page.locator("a[href$='/systems/jme/']").first().click();
            page.waitForURL("**/systems/jme/");

            PlaywrightAssertions.assertThat(page.getByText("jme-doc-service").first()).isVisible();
        }
    }

    /**
     * A diagram, which is the one thing about a generated site that no HTTP assertion can check: the generator
     * emits no image at all - a component's context view is a fenced PlantUML block, and it becomes a picture
     * only when the Docusaurus plugin renders it in the reader's browser. Over HTTP this page passes while
     * showing a wall of diagram source.
     */
    @Test
    @Order(11)
    void aContextDiagramIsRenderedInTheBrowser() {
        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, "/" + ENVIRONMENT + SYSTEM_CONTEXT_VIEW);

            // The svg that carries text, not the first one: the container also holds the toolbar's icons, and
            // an assertion matching one of those would pass with the diagram itself broken.
            Locator diagram = page.locator("[data-plantuml-diagram] svg:has(text)").first();
            PlaywrightAssertions.assertThat(diagram).isVisible();
            // What the picture is of. The neighbour is the whole reason the stubbed landscape has a second
            // system: a context view of one system alone would render just as well and prove nothing.
            PlaywrightAssertions.assertThat(diagram).containsText("orders");
            PlaywrightAssertions.assertThat(diagram).not().containsText("Syntax Error");
        }
    }

    /**
     * And the reaction graph, which is the other renderer: a runtime view is a <b>GraphViz</b> source block
     * where a context view is a PlantUML one, so a plugin registered for the one and not the other is a page
     * of source text that every HTTP assertion above passes.
     */
    @Test
    @Order(12)
    void aReactionGraphIsRenderedInTheBrowser() {
        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, "/" + ENVIRONMENT + SYSTEM_REACTIONS);

            Locator diagram = page.locator("[data-plantuml-diagram] svg:has(text)").first();
            PlaywrightAssertions.assertThat(diagram).isVisible();
            // What proves the source was parsed is the content: nothing at all is drawn for one that is not.
            // The labels are the names without the suffix every component and message type carries - a
            // picture says what it is of in the room it has, and the table beside it carries both in full.
            PlaywrightAssertions.assertThat(diagram).containsText("jme-doc");
            PlaywrightAssertions.assertThat(diagram).containsText("OrdersPaymentAccepted");
            PlaywrightAssertions.assertThat(diagram).not().containsText("Syntax Error");
        }
    }

    /**
     * And the other one: the search is an index downloaded by the page and queried in the browser, so a
     * request for the search page tells nothing about whether anything can be found.
     */
    @Test
    @Order(13)
    void theSearchFindsAGeneratedPageInTheBrowser() {
        // One index over the whole site, built at the end of the build pass that published the parts rather
        // than by any one of them - so it arrives after the pages do, and a site that is already being read
        // can be a site whose search is a moment behind.
        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(2))
                .until(() -> given().baseUri(DOC_BASE_URL).when().get(SEARCH_INDEX).getStatusCode() == 200);

        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, "/" + ENVIRONMENT + "/");

            Locator box = page.locator("input.navbar__search-input").first();
            PlaywrightAssertions.assertThat(box).isVisible();
            box.click();
            // Through the keyboard rather than into the element, and key by key. The box loads its index when
            // it is first used and re-renders while it does, so a handle typed into is detached under the
            // test - and a value that arrives in one go can land before anything is listening at all.
            page.keyboard().type("orders", new Keyboard.TypeOptions().setDelay(60));

            PlaywrightAssertions.assertThat(page.getByRole(AriaRole.OPTION).first()).isVisible();
        }
    }

    /**
     * What the generator has been doing, which is the answer to <i>why is this site not updating</i> without
     * reading a log: every run with the part it produced, its trigger, its state, what it cost, and the digest
     * of the content it wrote - which is what a later run compares against to decide whether that part has to
     * be generated at all.
     */
    @Test
    @Order(14)
    void theHistorySaysWhatTheGeneratorDid() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(BUILDS_PATH + "/" + publishedBuildId)
                .then()
                .statusCode(200)
                .body("part", equalTo(SHELL_PART))
                .body("state", equalTo("SUCCEEDED"))
                .body("startedAt", notNullValue())
                .body("finishedAt", notNullValue())
                .body("instance", notNullValue())
                .body("objectPrefix", equalTo(SITE + "/" + publishedBuildId))
                .body("pageCount", greaterThan(0))
                .body("sizeInBytes", greaterThan(0))
                .body("docusaurusMillis", greaterThan(0))
                .body("contentDigest", notNullValue())
                .body("failureReason", nullValue());

        assertThat(buildIds()).isSortedAccordingTo(Comparator.reverseOrder()).contains(publishedBuildId);
    }

    /**
     * The history of the whole site is every part's; the history of one part is where an operator looks when
     * one part of a site has stopped being published while the rest of it is fine.
     */
    @Test
    @Order(15)
    void theBuildsOfOnePartAreReadableOnTheirOwn() {
        JsonPath builds = readJson(SHELL_BUILDS_PATH);

        assertThat(builds.getList("id", Long.class)).contains(publishedBuildId);
        assertThat(builds.getList("part", String.class)).containsOnly(SHELL_PART);
    }

    /**
     * Where a generated part ends up: under the prefix its build record names, below the site prefix of the
     * instance, and tagged - a build id is used once, so nothing that is being read is ever written to.
     */
    @Test
    @Order(16)
    void theGeneratedSiteLiesInTheObjectStorageUnderThePrefixOfItsBuild() {
        String prefix = "sites/" + SITE + "/" + publishedBuildId + "/";

        try (S3Client objectStorage = objectStorage()) {
            List<S3Object> published = objectStorage.listObjectsV2(ListObjectsV2Request.builder()
                    .bucket(documentationBucket).prefix(prefix).build()).contents();

            assertThat(published).isNotEmpty()
                    .extracting(S3Object::key)
                    .contains(prefix + "index.html", prefix + ENVIRONMENT + "/index.html");

            List<Tag> tags = objectStorage.getObjectTagging(GetObjectTaggingRequest.builder()
                    .bucket(documentationBucket).key(prefix + "index.html").build()).tagSet();
            assertThat(tags).extracting(Tag::key, Tag::value).containsExactly(tuple(SITE_TAG_KEY, SITE_TAG_VALUE));
        }
    }

    /**
     * The other half of what an upload does, and the half a reader sees. The pipeline asks for nothing but the
     * upload; the part that carries its system is asked for because the site is configured to be published on
     * upload - which is the default, and is what makes documentation appear without anybody operating
     * anything.
     * <p>
     * <b>Two sets, and the second one is the case a model cannot cover.</b> One documents a component the
     * stubbed landscape holds, so its uploaded chapter stands beside the chapters the generator writes for it.
     * The other documents a component of the same system that <i>no</i> importer has ever seen -
     * {@code jme-doc-upstream-stub} is a module of this example and is deployed nowhere - and it is published
     * all the same, out of the upload alone.
     * <p>
     * <b>And the other shapes a set comes in</b>, which the steps after this one read: the system's own
     * documentation, a library of the system, and a microsite - HTML a build emitted, published as it is. All
     * of them are uploaded before anything is waited for, because they belong to one part and the requests
     * collapse into one build - when they arrive before the first build has started, which is not guaranteed,
     * so each page is waited for on its own.
     */
    @Test
    @Order(17)
    void anUploadIsPublishedIntoThePartThatCarriesItsSystem() {
        long before = newestBuildId();

        upload(DocumentationSets.parameters());
        upload(DocumentationSets.parametersFor(DocumentationSets.COMPONENT_OUTSIDE_THE_MODEL));
        upload(DocumentationSets.systemParameters(), DocumentationSets.systemBundle());
        upload(DocumentationSets.libraryParameters(), DocumentationSets.libraryBundle());
        upload(DocumentationSets.micrositeParameters(DocumentationSets.MICROSITE_TOPIC),
               DocumentationSets.micrositeBundle());

        JsonPath build = await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> buildAfter(before, "UPLOAD"), Objects::nonNull);

        assertThat(build.getString("part")).isEqualTo(JME_PART);
        assertThat(build.getString("state")).isEqualTo("SUCCEEDED");
    }

    /**
     * The uploaded page itself, read where a reader reaches it: below the component, in the arc42 chapter the
     * folder of the ZIP named, under the file's own name. <b>The number of the chapter is in the folder and
     * not in the URL</b> - the numbers are arc42's, and a link should survive a methodology that numbers its
     * chapters differently.
     * <p>
     * What is asserted is the body and the provenance. The body, because nothing is appended to it and nothing
     * in it is rewritten - a team's Markdown is not the service's to edit. The provenance, because it is the
     * one thing the service adds and the only way an uploaded page can carry any: it is rendered from the
     * front matter the service generated out of the upload's parameters, and it is what tells a reader that
     * this page was written by a team rather than generated.
     * <p>
     * <b>Every environment tree gets it.</b> An upload names no environment - what a team writes is about the
     * thing rather than about a stage - so the page is read under the main environment at the root as well as
     * under one of the others.
     * <p>
     * <b>And the picture beside it.</b> A set is Markdown and the images its pages show, and an image takes
     * another way through the service: it is not a page, it is stored and written byte for byte, and Docusaurus
     * renames it after its content and publishes it under {@code assets/} - a directory every part of the site
     * shares. So it is followed from the page to the file the site serves, and compared with what was uploaded.
     */
    @Test
    @Order(18)
    void theUploadedPageIsServedInEveryEnvironmentOfTheSite() {
        // The requests of the two uploads collapse into one build, and a second one starting in between would
        // publish the part again - so the page is waited for rather than assumed to be there already.
        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(2))
                .until(() -> given().baseUri(DOC_BASE_URL)
                        .when()
                        .get("/" + ENVIRONMENT + uploadedPageOf(DocumentationSets.COMPONENT))
                        .getStatusCode() == 200);

        for (String environment : ENVIRONMENTS) {
            String tree = environment.equals(MAIN_ENVIRONMENT) ? "" : "/" + environment;

            given().baseUri(DOC_BASE_URL)
                    .when()
                    .get(tree + uploadedPageOf(DocumentationSets.COMPONENT))
                    .then()
                    .statusCode(200)
                    .body(containsString(DocumentationSets.PAGE_TITLE))
                    .body(containsString(DocumentationSets.PAGE_TEXT))
                    // The provenance: the label the site template renders for a page whose doc_status is
                    // 'custom' - against the "Generated page" of everything the model produced - and the
                    // commit the upload named, which is where the page is to be edited.
                    .body(containsString("Uploaded"))
                    .body(containsString(DocumentationSets.SOURCE_REVISION));
        }

        assertThePictureOfTheUploadedPageIsServed();
    }

    private static void assertThePictureOfTheUploadedPageIsServed() {
        URI page = URI.create(DOC_BASE_URL + "/" + ENVIRONMENT + uploadedPageOf(DocumentationSets.COMPONENT));
        String html = given().when().get(page).then().statusCode(200).extract().asString();

        Matcher picture = UPLOADED_PICTURE.matcher(html);
        assertThat(picture.find()).describedAs("the page shows the picture uploaded beside it").isTrue();
        Matcher source = SOURCE.matcher(picture.group());
        assertThat(source.find()).describedAs("the picture has a source: %s", picture.group()).isTrue();
        String location = source.group(1) != null ? source.group(1) : source.group(2);
        assertThat(location)
                .describedAs("the picture is published as a file of its own rather than inlined into the page")
                .doesNotStartWith("data:");

        byte[] served = given().when()
                .get(page.resolve(location))
                .then()
                .statusCode(200)
                .contentType(containsString("image/png"))
                .extract().asByteArray();
        assertThat(served).isEqualTo(DocumentationSets.image());
    }

    /**
     * And the component the architecture model does not hold. A team can document something before anything is
     * deployed, and the service publishes it out of the upload alone: the component gets its tree in the
     * building block view of its system, the chapter the team wrote is in it, and chapter 1 additionally
     * carries a generated page saying that the model does not hold it.
     */
    @Test
    @Order(19)
    void aComponentTheArchitectureModelDoesNotHoldIsPublishedFromItsUploadAlone() {
        // Its own wait: when the first build had already started, this upload is published by the next one.
        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(2))
                .until(() -> given().baseUri(DOC_BASE_URL)
                        .when()
                        .get("/" + ENVIRONMENT + uploadedPageOf(DocumentationSets.COMPONENT_OUTSIDE_THE_MODEL))
                        .getStatusCode() == 200);

        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/" + ENVIRONMENT + uploadedPageOf(DocumentationSets.COMPONENT_OUTSIDE_THE_MODEL))
                .then()
                .statusCode(200)
                .body(containsString(DocumentationSets.PAGE_TEXT))
                .body(containsString("Uploaded"));

        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/" + ENVIRONMENT + componentTreeOf(DocumentationSets.COMPONENT_OUTSIDE_THE_MODEL))
                .then()
                .statusCode(200);
    }

    /**
     * The system's own documentation, and the one thing about an uploaded page only a browser can tell: <b>raw
     * HTML in it is shown as text and never applied</b>. The site's policy allows inline script, because the
     * colour mode needs it, so what keeps an uploaded {@code <script>} from running on this origin is that it
     * never becomes markup - and a build that let it through would be just as green.
     * <p>
     * <b>And the picture beside it is served sandboxed.</b> An SVG carries script, and opened on its own it
     * would run on this origin; served with {@code sandbox} in its policy, it runs on none.
     */
    @Test
    @Order(20)
    void theSystemsOwnPageShowsItsRawHtmlAsTextAndServesItsSvgSandboxed() {
        String route = "/" + ENVIRONMENT + SYSTEM_TREE + "constraints/" + DocumentationSets.RAW_HTML_PAGE_NAME + "/";
        awaitServed(route);

        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, route);

            PlaywrightAssertions.assertThat(page.getByText(DocumentationSets.RAW_SCRIPT)).isVisible();
            PlaywrightAssertions.assertThat(page.getByText(DocumentationSets.RAW_STYLE)).isVisible();
            assertThat(page.evaluate("() => window.UPLOADED_SCRIPT_RAN")).describedAs("the uploaded script ran")
                    .isNull();
            assertThat(page.evaluate("() => getComputedStyle(document.body).outlineWidth"))
                    .describedAs("the uploaded style was applied").isNotEqualTo("7px");
        }

        URI pageUri = URI.create(DOC_BASE_URL + route);
        String html = given().when().get(pageUri).then().statusCode(200).extract().asString();
        Matcher picture = Pattern.compile("<img[^>]*alt=\"" + Pattern.quote(DocumentationSets.SVG_ALT) + "\"[^>]*>")
                .matcher(html);
        assertThat(picture.find()).describedAs("the page shows the SVG uploaded beside it").isTrue();
        Matcher source = SOURCE.matcher(picture.group());
        assertThat(source.find()).isTrue();
        String location = source.group(1) != null ? source.group(1) : source.group(2);
        assertThat(location).describedAs("the SVG is published as a file of its own").doesNotStartWith("data:");

        given().when()
                .get(pageUri.resolve(location))
                .then()
                .statusCode(200)
                .header("Content-Security-Policy", containsString("sandbox"));
    }

    /**
     * A library, which no architecture model holds: its tree stands beside the components of its system, and
     * the chapter its team wrote is in it - out of the upload alone.
     */
    @Test
    @Order(21)
    void aLibraryIsPublishedBesideTheComponentsOfItsSystem() {
        String library = "/" + ENVIRONMENT + SYSTEM_TREE + "building-block-view/libraries/"
                         + DocumentationSets.LIBRARY + "/";
        String page = library + "library-architecture/glossary/" + DocumentationSets.LIBRARY_PAGE_NAME + "/";
        awaitServed(page);

        given().baseUri(DOC_BASE_URL)
                .when()
                .get(page)
                .then()
                .statusCode(200)
                .body(containsString(DocumentationSets.LIBRARY_PAGE_TEXT))
                .body(containsString("Uploaded"));
        given().baseUri(DOC_BASE_URL).when().get(library).then().statusCode(200);
    }

    /**
     * <b>A microsite is served inside the site's own navigation</b>: a page generated into the chapter its
     * upload named, with the navbar and the sidebar around a frame. The frame is sandboxed without
     * {@code allow-same-origin}, which is what gives the documentation inside it an origin of its own - and
     * the probe page of the fixture writes down what the browser let it do: its origin is opaque, the page
     * around it is out of reach, and storage works all the same, through the one script the service injects.
     * <p>
     * <b>And a microsite that says how tall it is gets a frame that tall.</b> The probe reports a height, and
     * the page grows the frame to it rather than leaving the reader a box with a scrollbar of its own.
     */
    @Test
    @Order(22)
    void theMicrositeIsFramedInsideTheSitesNavigationWithAnOriginOfItsOwn() {
        String route = "/" + ENVIRONMENT + micrositePageOf(DocumentationSets.MICROSITE_TOPIC);
        awaitServed(route);

        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, route);

            PlaywrightAssertions.assertThat(page.locator("nav.navbar")).isVisible();
            PlaywrightAssertions.assertThat(page.locator("nav.menu")).isVisible();
            Locator frame = page.locator("iframe");
            PlaywrightAssertions.assertThat(frame).isVisible();
            assertThat(frame.getAttribute("sandbox")).contains("allow-scripts").doesNotContain("allow-same-origin");

            Frame microsite = micrositeFrame(page);
            PlaywrightAssertions.assertThat(microsite.locator("h1")).hasText(DocumentationSets.MICROSITE_HEADING);
            assertThat(microsite.evaluate("() => window.ORIGIN")).isEqualTo("null");
            assertThat(microsite.evaluate("() => window.REACHED_PARENT")).isEqualTo(false);
            assertThat(microsite.evaluate("() => window.STORAGE_WORKED"))
                    .describedAs("the shim ran before the microsite's own script").isEqualTo(true);

            // In this thread: Playwright may only be called from the thread that created it, and blocks elsewhere.
            await().atMost(Duration.ofSeconds(15))
                    .pollInSameThread()
                    .pollInterval(Duration.ofMillis(250))
                    .until(() -> ((Number) frame.evaluate("f => f.getBoundingClientRect().height")).intValue()
                                 == DocumentationSets.MICROSITE_REPORTED_HEIGHT);
        }
    }

    /**
     * <b>A link into a microsite</b> is the page's route plus {@code ?path=} - what a search hit inside one is,
     * too - and it opens the file it names in the frame, with that file's own stylesheet.
     */
    @Test
    @Order(23)
    void aPathInTheQueryOpensThatPageOfTheMicrosite() {
        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, "/" + ENVIRONMENT + micrositePageOf(DocumentationSets.MICROSITE_TOPIC)
                                      + "?path=" + DocumentationSets.MICROSITE_NESTED_PAGE);

            Frame microsite = micrositeFrame(page);
            assertThat(microsite.url()).contains("/" + DocumentationSets.MICROSITE_NESTED_PAGE);
            PlaywrightAssertions.assertThat(microsite.locator("h1"))
                    .hasText(DocumentationSets.MICROSITE_NESTED_HEADING);
            assertThat(microsite.locator("h1").evaluate("h1 => getComputedStyle(h1).color"))
                    .isEqualTo(DocumentationSets.MICROSITE_NESTED_COLOUR);
        }
    }

    /**
     * What the site itself is served with, now that its pages frame uploaded HTML: its policy allows a frame of
     * its own origin, and nothing but a microsite is answered cross-origin - not a page, and not the API.
     */
    @Test
    @Order(24)
    void theSiteMayFrameItsOwnOriginAndOnlyAMicrositeIsAnsweredCrossOrigin() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/")
                .then()
                .statusCode(200)
                .header("Content-Security-Policy", containsString("frame-src 'self'"))
                .header("Access-Control-Allow-Origin", nullValue());

        given().baseUri(DOC_BASE_URL)
                .when()
                .get(SITE_PATH)
                .then()
                .statusCode(401)
                .header("Access-Control-Allow-Origin", nullValue());

        given().baseUri(DOC_BASE_URL)
                .when()
                .get(micrositeUrlOf(DocumentationSets.MICROSITE_TOPIC))
                .then()
                .statusCode(200)
                .header("Access-Control-Allow-Origin", "*");
    }

    /**
     * <b>The search finds what teams uploaded</b>, the text of a microsite included - which reaches the index
     * only because it was extracted from the bundle when it was uploaded, since a microsite's pages are in no
     * content tree. One word is on the uploaded Markdown page and inside the microsite and on no generated
     * page; and <b>the chips narrow by kind</b>: with uploaded Markdown turned off, the Markdown page is gone
     * and the microsite is still there, and the URL carries the selection.
     * <p>
     * <b>Which hits, not how many.</b> The containers of the example keep their data between runs and are
     * shared with {@code DocServiceExampleIT}, whose microsites carry the same word - so the pages of this suite
     * are looked for among the hits rather than counted.
     * <p>
     * The index is built at the end of the build pass, after the pages are published, so it is waited for.
     */
    @Test
    @Order(25)
    void theSearchFindsUploadedDocumentationAndTheChipsNarrowItByKind() {
        String query = "/search/?q=" + DocumentationSets.ON_BOTH_UPLOADED_KINDS;
        String markdownPage = SYSTEM_TREE + "constraints/" + DocumentationSets.RAW_HTML_PAGE_NAME + "/";
        String micrositePage = micrositePageOf(DocumentationSets.MICROSITE_TOPIC);
        await().atMost(BUILD_TIMEOUT)
                .pollInSameThread()
                .pollInterval(Duration.ofSeconds(3))
                .until(() -> {
                    List<String> hits = hitsOn(query);
                    return hits.stream().anyMatch(href -> href.endsWith(markdownPage))
                           && hits.stream().anyMatch(href -> href.endsWith(micrositePage));
                });

        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, query);
            PlaywrightAssertions.assertThat(hitTo(page, markdownPage)).hasCount(1);
            PlaywrightAssertions.assertThat(hitTo(page, micrositePage)).hasCount(1);

            chip(page, "Uploaded MD").click();

            page.waitForURL(url -> url.contains("source=generated%2Chtml"));
            PlaywrightAssertions.assertThat(chip(page, "Uploaded MD")).hasAttribute("aria-pressed", "false");
            PlaywrightAssertions.assertThat(hitTo(page, markdownPage)).hasCount(0);
            PlaywrightAssertions.assertThat(hitTo(page, micrositePage)).hasCount(1);
        }
    }

    /**
     * <b>A hit inside a microsite opens the page that frames it, at the file the word is on.</b> The word is
     * on a page below the entry point, so the hit carries {@code ?path=} and the frame shows that page.
     */
    @Test
    @Order(26)
    void aHitInsideTheMicrositeOpensItsFrameAtTheFileTheWordIsOn() {
        String query = "/search/?q=" + DocumentationSets.ONLY_INSIDE_THE_MICROSITE;
        // This suite's microsite, among the ones DocServiceExampleIT left with the same pages.
        String hitInside = micrositePageOf(DocumentationSets.MICROSITE_TOPIC) + "?path="
                           + DocumentationSets.MICROSITE_NESTED_PAGE;
        await().atMost(BUILD_TIMEOUT)
                .pollInSameThread()
                .pollInterval(Duration.ofSeconds(3))
                .until(() -> hitsOn(query).stream().anyMatch(href -> href.endsWith(hitInside)));

        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, query);

            Locator hit = hitTo(page, hitInside);
            PlaywrightAssertions.assertThat(hit).isVisible();
            hit.click();

            page.waitForURL("**?path=" + DocumentationSets.MICROSITE_NESTED_PAGE);
            page.waitForFunction("() => document.documentElement.dataset.hasHydrated === 'true'");
            PlaywrightAssertions.assertThat(micrositeFrame(page).locator("h1"))
                    .hasText(DocumentationSets.MICROSITE_NESTED_HEADING);
        }
    }

    /**
     * <b>Removing a set takes its files at once and its page with the next build.</b> The files are served
     * straight from the bucket, so they are gone as soon as the call answers - after the few seconds a
     * resolved prefix is cached. The page that framed them is part of a published build, which nothing edits,
     * so the removal asks for the part to be built and the page disappears with that build.
     */
    @Test
    @Order(27)
    void removingTheMicrositeTakesItsFilesAtOnceAndItsPageWithTheNextBuild() {
        long before = newestBuildId();
        Map<String, String> set = DocumentationSets.micrositeStructureParameters(DocumentationSets.MICROSITE_TOPIC);

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(uploadToken())
                .queryParams(set)
                .when()
                .delete(REMOVE_SETS_PATH)
                .then()
                .statusCode(200)
                .body("setsRemoved", equalTo(1))
                .body("buildAsked", equalTo(true));

        await().atMost(Duration.ofSeconds(30))
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> given().when().get(micrositeUrlOf(DocumentationSets.MICROSITE_TOPIC)).getStatusCode()
                             == 404);

        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(2))
                .until(() -> succeededBuildOfPartAfter(before, JME_PART));
        await().atMost(Duration.ofSeconds(30))
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> given().baseUri(DOC_BASE_URL).when()
                        .get("/" + ENVIRONMENT + micrositePageOf(DocumentationSets.MICROSITE_TOPIC))
                        .getStatusCode() == 404);
    }

    /**
     * One part on its own, which is what an operator asks for when one part of a site is wrong and the rest of
     * it is expensive to rebuild. The ask leaves the same collapsing request every other trigger leaves, and
     * unlike an upload it is the forcing kind: the part is published whether its content moved or not, which
     * is what is wanted after a change outside the content.
     */
    @Test
    @Order(28)
    void askingForOnePartPublishesItWhetherItsContentMovedOrNot() {
        long before = newestBuildId();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(SHELL_BUILDS_PATH)
                .then()
                .statusCode(202)
                .body("site", equalTo(SITE))
                .body("part", equalTo(SHELL_PART))
                .body("requested", equalTo(true))
                .body("trigger", equalTo("MANUAL"))
                .body("pendingSince", notNullValue())
                .body("picksUpWithinSeconds", equalTo(POLL_INTERVAL_SECONDS));

        awaitSucceededBuildAfter(before, "MANUAL");
    }

    /**
     * A part is looked up among the parts the site really has rather than derived from the identifier - so an
     * operator who asks for a part nothing documents is told so instead of watching an empty build published
     * under it.
     */
    @Test
    @Order(29)
    void askingForAPartTheSiteDoesNotHaveIsNotFound() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(PARTS_PATH + "/system-nobody-documents/builds")
                .then()
                .statusCode(404);
    }

    /**
     * A pipeline may not publish the site, and may not import the model either. Its role is granted per system
     * in the tenant part precisely so that it can only change its own system's documentation, and both of
     * these regenerate documentation of every system - so the upload role is not a lever over them, and
     * neither is the role that reads the upload API.
     */
    @Test
    @Order(30)
    void administeringWithAnythingButTheAdminRoleIsRejected() {
        String readerToken = fetchAccessToken(AUTH_BASE_URL, "jme-doc-reader", "secret");

        for (String path : List.of(BUILDS_PATH, SHELL_BUILDS_PATH, IMPORTS_PATH)) {
            assertThat(statusOfPosting(path, uploadToken())).isEqualTo(403);
            assertThat(statusOfPosting(path, readerToken)).isEqualTo(403);
        }
    }

    /**
     * And the other way round: the roles that administer a site do not let their holder change the
     * documentation of a system. The two resources are separate in both directions.
     */
    @Test
    @Order(31)
    void uploadingWithTheOperatorRoleIsRejected() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .contentType("application/zip")
                .queryParams(DocumentationSets.parameters())
                .body(DocumentationSets.bundle())
                .when()
                .put(UPLOAD_PATH + UUID.randomUUID())
                .then()
                .statusCode(403);
    }

    @Test
    @Order(32)
    void readingWhatTheGeneratorDidWithAnUploadRoleIsRejected() {
        for (String path : List.of(SITE_PATH, BUILDS_PATH, PARTS_PATH, SHELL_BUILDS_PATH, IMPORT_STATE_PATH)) {
            given().baseUri(DOC_BASE_URL)
                    .auth().oauth2(uploadToken())
                    .when()
                    .get(path)
                    .then()
                    .statusCode(403);
        }
    }

    @Test
    @Order(33)
    void administeringASiteWithoutATokenIsRejected() {
        for (String path : List.of(SITE_PATH, BUILDS_PATH, PARTS_PATH, SHELL_BUILDS_PATH, IMPORT_STATE_PATH)) {
            given().baseUri(DOC_BASE_URL).when().get(path).then().statusCode(401);
        }
        given().baseUri(DOC_BASE_URL).when().post(BUILDS_PATH).then().statusCode(401);
        given().baseUri(DOC_BASE_URL).when().post(IMPORTS_PATH).then().statusCode(401);
    }

    /**
     * <b>A second site, and one that needs no architecture model.</b> Its one environment has no architecture
     * repository behind it, so the import at the start of this suite - which asked for every part of every site
     * documenting the environments it read - asked for nothing on it, and no system of the model is a part of
     * it.
     * <p>
     * Whether it has been published is not asserted: the containers keep their data between runs, so a second
     * run finds what the first one published. Nothing is owed a build either way, because this suite switches
     * the reconcile schedule off - which is exactly the schedule that would publish a site like this one on a
     * real instance.
     */
    @Test
    @Order(34)
    void aSiteWithoutAnArchitectureModelIsLeftAloneByTheImport() {
        assertThat(readJson("/api/sites").getList("site", String.class)).containsExactlyInAnyOrder(SITE, HANDBOOK);

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(HANDBOOK_SITE_PATH)
                .then()
                .statusCode(200)
                .body("title", equalTo(HANDBOOK_TITLE))
                .body("environments", contains("current"))
                .body("pending", nullValue())
                .body("running", empty());
        assertThat(readJson(HANDBOOK_SITE_PATH + "/parts").getList("part", String.class))
                .contains(SHELL_PART)
                .doesNotContain(ORDERS_PART);
    }

    /**
     * An operator publishes it, and it is served below {@code /site/handbook/} with the title and the tagline
     * it is configured with. Nothing of the model is on it, and the page about the documentation says that the
     * site does not wait for one - and that an upload is what publishes it.
     */
    @Test
    @Order(35)
    void anOperatorPublishesTheSiteBelowItsOwnPathWithoutAModel() {
        long before = newestBuildIdOf(HANDBOOK);
        int parts = readJson(HANDBOOK_SITE_PATH + "/parts").getList("part").size();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(HANDBOOK_SITE_PATH + "/builds")
                .then()
                .statusCode(202)
                .body("site", equalTo(HANDBOOK))
                .body("partsRequested", equalTo(parts));

        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> succeededBuildOfPartAfter(HANDBOOK, before, SHELL_PART));
        // An instance re-reads which build of a site is published on jeap.doc.publication.refresh rather than
        // per request, so a site published for the first time is served a moment after its build.
        awaitServed(HANDBOOK_ROOT);

        given().baseUri(DOC_BASE_URL)
                .when()
                .get(HANDBOOK_ROOT)
                .then()
                .statusCode(200)
                .body(containsString(HANDBOOK_TITLE))
                .body(containsString(HANDBOOK_TAGLINE));
        String about = given().baseUri(DOC_BASE_URL)
                .when()
                .get(HANDBOOK_ROOT + "about-this-documentation/")
                .then()
                .statusCode(200)
                .extract().asString();
        assertThat(about).containsPattern("Waits for the architecture model(?:\\s|<[^>]*>)*no<")
                .contains("only when something is uploaded to this site");

        assertThat(readJson(PARTS_PATH).getList("part", String.class))
                .containsExactlyInAnyOrder(SHELL_PART, JME_PART, ORDERS_PART);
    }

    /**
     * An upload naming the site is published there, into the part of its system - and only there: the build is
     * in the handbook's history, and the default site was asked for nothing.
     */
    @Test
    @Order(36)
    void anUploadNamingTheSiteIsPublishedThere() {
        long before = Math.max(newestBuildIdOf(SITE), newestBuildIdOf(HANDBOOK));

        upload(DocumentationSets.handbookParameters(), DocumentationSets.handbookBundle());

        JsonPath build = await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> buildAfter(HANDBOOK, before, "UPLOAD"), Objects::nonNull);

        assertThat(build.getString("part")).isEqualTo(JME_PART);
        assertThat(build.getString("state")).isEqualTo("SUCCEEDED");
        assertThat(buildAfter(SITE, before, "UPLOAD")).isNull();
        assertThat(readJson(HANDBOOK_SITE_PATH + "/parts").getList("part", String.class))
                .containsExactlyInAnyOrder(SHELL_PART, JME_PART);
    }

    /**
     * What the handbook serves is what was uploaded to it and nothing of the model. The system is one the model
     * of the default site holds, and on the handbook chapter 1 says the model does not hold it - which is true:
     * a site reads only the models of its own environments, and this one reads none. And the two sites keep
     * their sets apart: the default site has no such page, and its own set of the same system is untouched.
     */
    @Test
    @Order(37)
    void theSiteServesWhatWasUploadedAndNothingOfTheModel() {
        String handbookSystemTree = "/site/" + HANDBOOK + SYSTEM_TREE;
        String handbookPage = "crosscutting-concepts/" + DocumentationSets.HANDBOOK_PAGE_NAME + "/";
        awaitServed(handbookSystemTree + handbookPage);

        given().baseUri(DOC_BASE_URL)
                .when()
                .get(handbookSystemTree + handbookPage)
                .then()
                .statusCode(200)
                .body(containsString("How we release"))
                .body(containsString(DocumentationSets.HANDBOOK_PAGE_TEXT))
                .body(containsString("Uploaded"))
                .body(containsString(DocumentationSets.SOURCE_REVISION));
        given().baseUri(DOC_BASE_URL)
                .when()
                .get(handbookSystemTree + "intro/not-in-the-architecture-model/")
                .then()
                .statusCode(200);
        for (String generatedByTheModel : List.of("context-and-scope/", "building-block-view/")) {
            given().baseUri(DOC_BASE_URL).when().get(handbookSystemTree + generatedByTheModel)
                    .then().statusCode(404);
        }
        given().baseUri(DOC_BASE_URL).when().get(HANDBOOK_ROOT + "systems/orders/").then().statusCode(404);

        given().baseUri(DOC_BASE_URL).when().get(SYSTEM_TREE + handbookPage).then().statusCode(404);
        given().baseUri(DOC_BASE_URL)
                .when()
                .get(SYSTEM_TREE + "constraints/" + DocumentationSets.RAW_HTML_PAGE_NAME + "/")
                .then()
                .statusCode(200);
    }

    /**
     * In the browser: the handbook looks like its own site, and it searches its own index. Each search is asked
     * for a word it has, which is what makes the word it does not have a finding rather than an index that had
     * not loaded yet.
     */
    @Test
    @Order(38)
    void theSiteHasItsOwnLookAndItsOwnSearchInTheBrowser() {
        try (BrowserContext context = browser.newContext()) {
            assertThat(primaryColourOf(open(context, HANDBOOK_ROOT))).isEqualTo(NEUTRAL_PRIMARY_COLOUR);
            assertThat(primaryColourOf(open(context, "/"))).isNotEqualTo(NEUTRAL_PRIMARY_COLOUR);
        }

        String handbookPage = "/site/" + HANDBOOK + SYSTEM_TREE + "crosscutting-concepts/"
                              + DocumentationSets.HANDBOOK_PAGE_NAME + "/";
        await().atMost(BUILD_TIMEOUT)
                .pollInSameThread()
                .pollInterval(Duration.ofSeconds(3))
                .until(() -> hitsOn(HANDBOOK_ROOT + "search/?q=" + DocumentationSets.ON_THE_HANDBOOK_ONLY)
                        .stream().anyMatch(href -> href.endsWith(handbookPage)));

        assertThat(hitsOn("/search/?q=" + DocumentationSets.ON_BOTH_UPLOADED_KINDS)).isNotEmpty();
        assertThat(hitsOn("/search/?q=" + DocumentationSets.ON_THE_HANDBOOK_ONLY)).isEmpty();
        assertThat(hitsOn(HANDBOOK_ROOT + "search/?q=" + DocumentationSets.ON_BOTH_UPLOADED_KINDS)).isEmpty();
    }

    /**
     * A site is configuration, so a site this instance does not configure is a typo in the request rather than
     * something that might appear later - and it is refused rather than answered with an empty history.
     */
    @Test
    @Order(39)
    void askingForABuildOfASiteThisInstanceDoesNotConfigureIsNotFound() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post("/api/sites/" + UNCONFIGURED_SITE + "/builds")
                .then()
                .statusCode(404);
    }

    /**
     * Asking for the whole site: the answer is a {@code 202} saying how many parts are now owed a build and
     * how long it takes at most until an instance claims one. It is the forcing kind of ask - every part is
     * published whether its content moved or not - which is what an operator wants after a change outside the
     * content, the site template most of all.
     * <p>
     * <b>Last, and nothing is waited for.</b> What this leaves behind is three more generator runs producing
     * exactly what is already published, and the suite has read everything it came for.
     */
    @Test
    @Order(40)
    void askingForTheWholeSiteAsksForEveryPartOfIt() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(BUILDS_PATH)
                .then()
                .statusCode(202)
                .body("site", equalTo(SITE))
                .body("partsRequested", equalTo(3))
                .body("picksUpWithinSeconds", equalTo(POLL_INTERVAL_SECONDS));
    }

    /** Uploads the documentation set of this example under a fresh upload id. */
    private void upload(Map<String, String> parameters) {
        upload(parameters, DocumentationSets.bundle());
    }

    /** Waits until a page is served, for the pages the collapsed builds of the uploads publish one by one. */
    private static void awaitServed(String path) {
        await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(2))
                .until(() -> given().baseUri(DOC_BASE_URL).when().get(path).getStatusCode() == 200);
    }

    /** Where the page framing a microsite of the component is served, below the tree of an environment. */
    private static String micrositePageOf(String topic) {
        return componentTreeOf(DocumentationSets.COMPONENT) + "component-architecture/crosscutting-concepts/microsites/"
               + topic + "/";
    }

    /** And where the microsite itself is served: below the site's root, outside every environment tree. */
    private static String micrositeUrlOf(String topic) {
        return DOC_BASE_URL + "/microsites/" + DocumentationSets.SYSTEM + "/components/"
               + DocumentationSets.COMPONENT + "/arc42/" + DocumentationSets.MICROSITE_LOCATION + "/" + topic + "/";
    }

    /**
     * The frame the microsite is in, once it has loaded. The page's own route carries {@code microsites/} too,
     * so the frame is told from the page by the prefix the microsite is served under.
     */
    private static Frame micrositeFrame(Page page) {
        page.frameLocator("iframe").locator("body").waitFor();
        String served = "/microsites/" + DocumentationSets.SYSTEM + "/components/";
        return page.frames().stream()
                .filter(frame -> !frame.equals(page.mainFrame()))
                .filter(frame -> frame.url().contains(served))
                .findFirst()
                .orElseThrow(() -> new AssertionError("the page frames no microsite served under " + served));
    }

    /** The results on the search page, by the name of their list - the navigation is full of links too. */
    private static Locator searchResultsOf(Page page) {
        return page.getByRole(AriaRole.LIST, new Page.GetByRoleOptions().setName("Search results"))
                .locator("li a[href]");
    }

    private static Locator chip(Page page, String label) {
        return page.getByRole(AriaRole.GROUP, new Page.GetByRoleOptions().setName("Narrow the results"))
                .getByRole(AriaRole.BUTTON, new Locator.GetByRoleOptions().setName(label)).first();
    }

    /**
     * Where the results the search page answers for a query now lead, or nothing while there are none yet. It
     * drives the browser, so an await polling it has to poll in this thread: Playwright may only be called from
     * the thread that created it.
     */
    private static List<String> hitsOn(String query) {
        try (BrowserContext context = browser.newContext()) {
            Page page = open(context, query);
            Locator hits = searchResultsOf(page);
            try {
                hits.first().waitFor(new Locator.WaitForOptions().setTimeout(5_000));
            } catch (TimeoutError nothingYet) {
                return List.of();
            }
            return hits.all().stream().map(hit -> hit.getAttribute("href")).toList();
        }
    }

    /** The primary colour of the scheme the page is drawn in, as the site's stylesheet defines it. */
    private static String primaryColourOf(Page page) {
        return String.valueOf(page.evaluate(
                "() => getComputedStyle(document.documentElement).getPropertyValue('--ifm-color-primary').trim()"));
    }

    /** The result on the search page that leads to the given route - whatever else the site holds. */
    private static Locator hitTo(Page page, String route) {
        return searchResultsOf(page).and(page.locator("a[href$='" + route + "']"));
    }

    /** Whether a build of the part newer than the given id has succeeded, whatever asked for it. */
    private boolean succeededBuildOfPartAfter(long previousNewestBuildId, String part) {
        return succeededBuildOfPartAfter(SITE, previousNewestBuildId, part);
    }

    private boolean succeededBuildOfPartAfter(String site, long previousNewestBuildId, String part) {
        return history(site).getList("findAll { it.state == 'SUCCEEDED' && it.part == '%s' }.id".formatted(part),
                        Long.class).stream()
                .anyMatch(id -> id > previousNewestBuildId);
    }

    /** Uploads a set under a fresh upload id. */
    private void upload(Map<String, String> parameters, byte[] bundle) {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(uploadToken())
                .contentType("application/zip")
                .queryParams(parameters)
                .body(bundle)
                .when()
                .put(UPLOAD_PATH + UUID.randomUUID())
                .then()
                .statusCode(201);
    }

    /** Where one component of the system {@code jme} is documented, below the tree of an environment. */
    private static String componentTreeOf(String component) {
        return "/systems/" + DocumentationSets.SYSTEM + "/system-architecture/building-block-view/components/"
               + component + "/";
    }

    /** And where the page uploaded for it is served: its chapter, then the name the file had in the ZIP. */
    private static String uploadedPageOf(String component) {
        return componentTreeOf(component) + "component-architecture/" + UPLOADED_CHAPTER_SEGMENT + "/"
               + DocumentationSets.PAGE_NAME + "/";
    }

    /**
     * Opens a page of the site and waits until the application has taken over. Every browser assertion here is
     * about what the application does - a diagram it rendered, an index it queried - and the markup the
     * service answered with would report some of them wrongly.
     */
    private static Page open(BrowserContext context, String path) {
        Page page = context.newPage();
        page.setDefaultTimeout(20_000);
        page.navigate(DOC_BASE_URL + path);
        page.waitForFunction("() => document.documentElement.dataset.hasHydrated === 'true'");
        return page;
    }

    /**
     * When each step of each environment's import last succeeded, null where one never has.
     * <p>
     * <b>Every step and not only the model</b>, because the reactions are steps of the same import that run
     * after it, and the documentation of an environment is asked for once its whole chain has run - so a site
     * read as soon as the model is in is a site read before its runtime views exist.
     */
    private List<String> importedAt() {
        JsonPath state = readJson(IMPORT_STATE_PATH);
        List<String> succeededAt = new ArrayList<>();
        for (int environment = 0; environment < ENVIRONMENTS.size(); environment++) {
            succeededAt.addAll(
                    state.getList("[%d].imports.lastSuccessAt".formatted(environment), String.class));
        }
        return succeededAt;
    }

    /** Whether every part of the site is serving something and none of them is waiting for a build. */
    private boolean everyPartIsPublished() {
        JsonPath parts = readJson(PARTS_PATH);
        return parts.getList("part", String.class).size() == 3
               && !parts.getList("publishedAt", String.class).contains(null)
               && !parts.getList("owedABuild", Boolean.class).contains(true);
    }

    /**
     * Waits for the build one of this suite's asks led to, and answers its id. It has to be a newer build than
     * what stood before, so that a run left over from an earlier suite - or from an earlier run against the
     * same containers, which keep their data while they are left running - can never be mistaken for the one
     * just asked for.
     */
    private long awaitSucceededBuildAfter(long previousNewestBuildId, String trigger) {
        String succeededBuildsOfThatTrigger =
                "findAll { it.state == 'SUCCEEDED' && it.trigger == '%s' }.id".formatted(trigger);
        return await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> history().getList(succeededBuildsOfThatTrigger, Long.class).stream()
                        .filter(id -> id > previousNewestBuildId)
                        .max(Comparator.naturalOrder())
                        .orElse(null), Objects::nonNull);
    }

    /** The newest finished build of that trigger after the given id, whatever became of it, or null. */
    private JsonPath buildAfter(long previousNewestBuildId, String trigger) {
        return buildAfter(SITE, previousNewestBuildId, trigger);
    }

    private JsonPath buildAfter(String site, long previousNewestBuildId, String trigger) {
        JsonPath history = history(site);
        List<Long> ids = history.getList(
                "findAll { it.trigger == '%s' && it.state != 'RUNNING' }.id".formatted(trigger), Long.class);
        return ids.stream()
                .filter(id -> id > previousNewestBuildId)
                .max(Comparator.naturalOrder())
                .map(id -> readJson("/api/sites/" + site + "/builds/" + id))
                .orElse(null);
    }

    /** The published build of one part, which is what the parts endpoint says is being served for it. */
    private long publishedBuildIdOf(String part) {
        return readJson(PARTS_PATH + "/" + part + "/builds")
                .getList("findAll { it.state == 'SUCCEEDED' }.id", Long.class).stream()
                .mapToLong(Long::longValue)
                .max()
                .orElseThrow();
    }

    /** The newest build of the site, or zero when it has never been built - the ids come from a sequence. */
    private long newestBuildId() {
        return newestBuildIdOf(SITE);
    }

    private long newestBuildIdOf(String site) {
        return history(site).getList("id", Long.class).stream().mapToLong(Long::longValue).max().orElse(0);
    }

    private List<Long> buildIds() {
        return history().getList("id", Long.class);
    }

    /** The build history of every part of the site, newest first, read with the role that may read it. */
    private JsonPath history() {
        return history(SITE);
    }

    private JsonPath history(String site) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .queryParam("limit", 100)
                .when()
                .get("/api/sites/" + site + "/builds")
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
    }

    private JsonPath readJson(String path) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(path)
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
    }

    private int statusOfPosting(String path, String accessToken) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(accessToken)
                .when()
                .post(path)
                .then()
                .extract()
                .statusCode();
    }

    private String uploadToken() {
        return fetchAccessToken(AUTH_BASE_URL, "jme-doc-pipeline", "secret");
    }

    private String operatorToken() {
        return fetchAccessToken(AUTH_BASE_URL, "jme-doc-operator", "secret");
    }

    /**
     * A client for the object storage of the example. Path style addressing, because the bucket of a local
     * S3-compatible storage is a path and not a subdomain.
     */
    private S3Client objectStorage() {
        return S3Client.builder()
                .endpointOverride(objectStorageEndpoint)
                .region(Region.of(objectStorageRegion))
                .credentialsProvider(StaticCredentialsProvider.create(
                        AwsBasicCredentials.create(objectStorageAccessKey, objectStorageSecretKey)))
                .forcePathStyle(true)
                .build();
    }
}
