package ch.admin.bit.jeap.jme.doc;

import ch.admin.bit.jeap.jme.test.BootServiceSpringIntegrationTestBase;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Value;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectTaggingRequest;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
import software.amazon.awssdk.services.s3.model.S3Object;
import software.amazon.awssdk.services.s3.model.Tag;

import java.net.URI;
import java.time.Duration;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.empty;
import static org.hamcrest.Matchers.endsWith;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.nullValue;

/**
 * Generates the documentation site of this example and reads what the generator did, with tokens of the OAuth
 * mock server.
 * <p>
 * This is the half of the doc service that publishes rather than receives, and it is what makes the example need
 * Node: the site is generated by running the site generator as a child process. So this is the suite that fails
 * when the local development environment is not set up - if the doc service never becomes ready here, its
 * {@code jeap.doc.build.*} configuration is where to look, and {@code docs/local-development.md} says what it
 * has to point at.
 * <p>
 * <b>A site is published as one build per part</b>, not as one build of the whole. A part is a set of whole URL
 * subtrees, and the partition cuts a site into one part per system plus the <i>shell</i> - the part carrying the
 * site's own pages and everything no system claims. Which systems a site has is what an architecture repository
 * tells it, and <b>this example configures none</b>: its site is the shell and nothing else, which is a
 * legitimate configuration and the smallest one there is. Everything below is therefore about one part, and the
 * parts endpoint is where an instance with a landscape behind it would show a great many.
 * <p>
 * <b>Administering a site is not a system's own business.</b> The upload roles carry the system in their tenant
 * part so that a pipeline can only change its own documentation, while a build regenerates a part with the
 * documentation of every repository in it - so it is granted on a resource of its own that no pipeline holds.
 * <p>
 * The tests are ordered because they are one story: an operator asks for the site, it is published, and
 * everything after that reads what that build left behind. That several triggers collapse into a single build is
 * not asserted here - that is the doc service's own behaviour and is covered there. This suite is about the
 * instance being wired up correctly.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DocSiteExampleIT extends BootServiceSpringIntegrationTestBase {

    private static final List<Integer> SERVICE_PORTS = reserveFreePorts(2);
    private static final int AUTH_PORT = SERVICE_PORTS.getFirst();
    private static final int DOC_PORT = SERVICE_PORTS.get(1);
    private static final String AUTH_BASE_URL = "http://localhost:" + AUTH_PORT + "/jme-doc-auth-scs";
    private static final String DOC_BASE_URL = "http://localhost:" + DOC_PORT + "/jme-doc-service";

    /**
     * The only site this example configures. It is served at the context root, and it is the site an upload that
     * names none belongs to.
     */
    private static final String SITE = "default";

    /**
     * The part that carries the site's own pages - its root page, the systems index, the page about the
     * documentation - and everything no other part claims. It is the one part every site has whatever the
     * architecture model holds, and here it is the only one.
     */
    private static final String SHELL_PART = "shell";

    private static final String SITE_PATH = "/api/sites/" + SITE;
    private static final String BUILDS_PATH = SITE_PATH + "/builds";
    private static final String PARTS_PATH = SITE_PATH + "/parts";
    private static final String SHELL_BUILDS_PATH = PARTS_PATH + "/" + SHELL_PART + "/builds";
    private static final String UPLOAD_PATH = "/api/uploads/docs/";

    /** What the site of this example calls itself - configured in the instance, and read back off the page. */
    private static final String SITE_TITLE = "JME Documentation";

    /**
     * How often the instance under test looks whether a build has been asked for. Far below the 30 seconds of a
     * real instance, because every test here waits for a build: it is the one number that decides how long this
     * suite takes, and the endpoints answer it as {@code picksUpWithinSeconds}, which is asserted below.
     */
    private static final int POLL_INTERVAL_SECONDS = 2;

    /**
     * How long a build may take before the suite gives up on it. Generously above the twenty to thirty seconds
     * the site generator needs, because the first run on a cold machine has a bundler to warm up.
     */
    private static final Duration BUILD_TIMEOUT = Duration.ofMinutes(5);

    /**
     * The tag every file of a generated site carries - see docker/docker-compose.yml. The bundle of an upload
     * carries the same key with the value {@code upload}, which is what lets the lifecycle rule of the bucket
     * expire the bundles without touching the sites.
     */
    private static final String SITE_TAG_KEY = "jeap-doc-content";
    private static final String SITE_TAG_VALUE = "site";

    /** The build this suite published, so that everything read afterwards is read about that build and no other. */
    private static long publishedBuildId;

    @Value("${jme-doc-test.objectstorage.endpoint-url}")
    private URI objectStorageEndpoint;
    @Value("${jme-doc-test.objectstorage.region}")
    private String objectStorageRegion;
    @Value("${jme-doc-test.objectstorage.access-key}")
    private String objectStorageAccessKey;
    @Value("${jme-doc-test.objectstorage.secret-key}")
    private String objectStorageSecretKey;
    @Value("${jme-doc-test.objectstorage.bucket}")
    private String documentationBucket;

    /**
     * Three settings of the doc service are the suite's rather than the instance's, and each one is here to make
     * an outcome of this suite the outcome of something it did:
     * <ul>
     *   <li>the poll interval, so a build starts seconds after it is asked for instead of within half a minute;
     *   <li>no reconcile schedule, so the only builds that happen are the ones these tests ask for - it is the
     *       schedule that publishes a site no architecture import feeds, which is exactly this one;
     *   <li>the publication URL, which names the origin in the metadata of the generated pages - and the service
     *       runs on a free port here rather than on the 8080 the instance configures.
     * </ul>
     * Everything else - where Node is, where the site template's dependencies are, what the site is called - is
     * the instance's own configuration, which is what this suite is here to exercise.
     */
    @BeforeAll
    static void startServices() throws Exception {
        startService("jme-doc-auth-scs", AUTH_BASE_URL, Map.of(
                "server.port", String.valueOf(AUTH_PORT),
                "mockserver.base-url", AUTH_BASE_URL));
        startService("jme-doc-service", DOC_BASE_URL, Map.of(
                "server.port", String.valueOf(DOC_PORT),
                "jeap.security.oauth2.resourceserver.authorization-server.issuer", AUTH_BASE_URL,
                "jeap.security.oauth2.resourceserver.authorization-server.jwk-set-uri",
                AUTH_BASE_URL + "/.well-known/jwks.json",
                "jeap.doc.build.poll-interval", "PT" + POLL_INTERVAL_SECONDS + "S",
                "jeap.doc.build.reconcile-cron", "-",
                "jeap.doc.publication.url", "http://localhost:" + DOC_PORT));
    }

    /**
     * Asking is not building: the answer is a 202 saying how many parts are now owed a build and how long it
     * takes at most until an instance claims one, and the builds then happen on that instance rather than on the
     * request thread. One part here, and the ask is the forcing kind - every part is published whether its
     * content moved or not, which is what an operator wants after a change outside the content.
     */
    @Test
    @Order(1)
    void askingForTheWholeSitePublishesEveryPartOfIt() {
        long before = newestBuildId();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(BUILDS_PATH)
                .then()
                .statusCode(202)
                .body("site", equalTo(SITE))
                .body("partsRequested", equalTo(1))
                .body("picksUpWithinSeconds", equalTo(POLL_INTERVAL_SECONDS));

        publishedBuildId = awaitSucceededBuildAfter(before, "MANUAL");

        JsonPath status = readJson(SITE_PATH);
        assertThat(status.getString("site")).isEqualTo(SITE);
        assertThat(status.getString("title")).isEqualTo(SITE_TITLE);
        assertThat(status.getList("environments", String.class)).containsExactly("dev", "ref", "abn", "prod");
        assertThat(status.getBoolean("publishOnUpload")).isTrue();
        // The shell's publication, which is what says the site is being served at all.
        assertThat(status.getLong("published.id")).isEqualTo(publishedBuildId);
        assertThat(status.getString("published.part")).isEqualTo(SHELL_PART);
    }

    /**
     * What the site is published as, and the answer to <i>is this documentation up to date</i> now that no
     * single build is the site: per part what it carries, what is published for it, how old that is and whether
     * a build of it is owed. A part nobody has rebuilt for a week either has not changed for a week or has
     * stopped being built, and the two are told apart by whether any other part is younger.
     */
    @Test
    @Order(2)
    void theSiteIsPublishedAsPartsAndHereTheShellIsTheOnlyOne() {
        JsonPath parts = readJson(PARTS_PATH);

        assertThat(parts.getList("part", String.class)).containsExactly(SHELL_PART);

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(PARTS_PATH)
                .then()
                .statusCode(200)
                .body("[0].documents", equalTo("the site itself"))
                .body("[0].environments", equalTo(List.of("dev", "ref", "abn", "prod")))
                // The shell owns no subtree of its own: it answers for whatever no other part claims.
                .body("[0].routePrefixes", empty())
                .body("[0].publishedAt", notNullValue())
                .body("[0].ageSeconds", notNullValue())
                .body("[0].contentDigest", notNullValue())
                .body("[0].owedABuild", equalTo(false));
    }

    /**
     * The documentation is served to anyone who can reach the service, and the API is not - which is the whole of
     * that decision, seen from outside. What the page says comes from the instance: the title is the one
     * configured in its application.yml, and the root of the site is its main environment.
     */
    @Test
    @Order(3)
    void theSiteIsServedToAnyoneWithoutAToken() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/")
                .then()
                .statusCode(200)
                .body(containsString(SITE_TITLE))
                .body(containsString("Production"));
    }

    /**
     * Every environment of the site is a tree of its own below it, and the main one is additionally served at the
     * root. The site is generated with a trailing slash on every route, so the form without one is a redirect
     * rather than a second URL for the same page.
     */
    @Test
    @Order(4)
    void everyEnvironmentIsServedUnderItsOwnPath() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/dev/")
                .then()
                .statusCode(200)
                .body(containsString("Development"));

        given().baseUri(DOC_BASE_URL)
                .redirects().follow(false)
                .when()
                .get("/dev")
                .then()
                .statusCode(301)
                .header("Location", endsWith("/dev/"));
    }

    /**
     * The site has a search of its own, at a page of its own, and it is served to a reader without a token like
     * the rest of the documentation. The index behind it is built at the end of the build pass that published
     * the site - not on a schedule, and never able to fail a publication.
     */
    @Test
    @Order(5)
    void theSiteHasASearchPage() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/search/")
                .then()
                .statusCode(200)
                .body(containsString("Search"));
    }

    /**
     * The site brings its own not-found page, and it is served with the status that says so - a reader gets the
     * navigation of the documentation they were looking for rather than an error page of the service.
     */
    @Test
    @Order(6)
    void anUnknownPageIsAnsweredWithTheSitesOwnNotFoundPage() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/nothing-was-published-here/")
                .then()
                .statusCode(404)
                .body(containsString("Page Not Found"));
    }

    /**
     * What the generator has been doing, which is the answer to <i>why is this site not updating</i> without
     * reading a log: every run with the part it produced, its trigger, its state, what it cost, and the digest of
     * the content it wrote - which is what a later run compares against to decide whether that part has to be
     * generated at all.
     */
    @Test
    @Order(7)
    void theHistorySaysWhatTheGeneratorDid() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(BUILDS_PATH + "/" + publishedBuildId)
                .then()
                .statusCode(200)
                .body("part", equalTo(SHELL_PART))
                .body("trigger", equalTo("MANUAL"))
                .body("state", equalTo("SUCCEEDED"))
                .body("startedAt", notNullValue())
                .body("finishedAt", notNullValue())
                .body("instance", notNullValue())
                .body("objectPrefix", equalTo(SITE + "/" + publishedBuildId))
                .body("pageCount", greaterThan(0))
                .body("sizeInBytes", greaterThan(0))
                .body("docusaurusMillis", greaterThan(0))
                .body("contentDigest", notNullValue())
                .body("failureReason", nullValue());

        assertThat(buildIds()).isSortedAccordingTo(Comparator.reverseOrder()).contains(publishedBuildId);
    }

    /**
     * The history of the whole site is every part's; the history of one part is where an operator looks when one
     * part of a site has stopped being published while the rest of it is fine.
     */
    @Test
    @Order(8)
    void theBuildsOfOnePartAreReadableOnTheirOwn() {
        JsonPath builds = readJson(SHELL_BUILDS_PATH);

        assertThat(builds.getList("id", Long.class)).contains(publishedBuildId);
        assertThat(builds.getList("part", String.class)).containsOnly(SHELL_PART);
    }

    /**
     * Where a generated site ends up: under the prefix the build record names, below the site prefix of the
     * instance, and tagged - a build id is used once, so nothing that is being read is ever written to.
     */
    @Test
    @Order(9)
    void theGeneratedSiteLiesInTheObjectStorageUnderThePrefixOfItsBuild() {
        String prefix = "sites/" + SITE + "/" + publishedBuildId + "/";

        try (S3Client objectStorage = objectStorage()) {
            List<S3Object> published = objectStorage.listObjectsV2(ListObjectsV2Request.builder()
                    .bucket(documentationBucket).prefix(prefix).build()).contents();

            assertThat(published).isNotEmpty()
                    .extracting(S3Object::key)
                    .contains(prefix + "index.html", prefix + "dev/index.html");

            List<Tag> tags = objectStorage.getObjectTagging(GetObjectTaggingRequest.builder()
                    .bucket(documentationBucket).key(prefix + "index.html").build()).tagSet();
            assertThat(tags).extracting(Tag::key, Tag::value).containsExactly(tuple(SITE_TAG_KEY, SITE_TAG_VALUE));
        }
    }

    /**
     * One part on its own, which is what an operator asks for when one part of a site is wrong and the rest of it
     * is expensive to rebuild. The ask leaves the same collapsing request every other trigger leaves, so an ask
     * that joins one already pending is answered {@code requested=false} and the same 202.
     */
    @Test
    @Order(10)
    void askingForOnePartAsksForThatPartAlone() {
        long before = newestBuildId();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(SHELL_BUILDS_PATH)
                .then()
                .statusCode(202)
                .body("site", equalTo(SITE))
                .body("part", equalTo(SHELL_PART))
                .body("requested", equalTo(true))
                .body("trigger", equalTo("MANUAL"))
                .body("pendingSince", notNullValue())
                .body("picksUpWithinSeconds", equalTo(POLL_INTERVAL_SECONDS));

        awaitSucceededBuildAfter(before, "MANUAL");
    }

    /**
     * A part is looked up among the parts the site really has rather than derived from the identifier. This
     * example documents no system, so {@code system-jme} is a part of no site here - and an operator who asks for
     * one is told so instead of watching an empty build be published under it.
     */
    @Test
    @Order(11)
    void askingForAPartTheSiteDoesNotHaveIsNotFound() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(PARTS_PATH + "/system-" + DocumentationSets.SYSTEM + "/builds")
                .then()
                .statusCode(404);
    }

    /**
     * A pipeline may not publish the site. Its role is granted per system in the tenant part precisely so that it
     * can only change its own system's documentation, and a build republishes a part with the documentation of
     * every repository in it - so the upload role is not a lever over it, and neither is the role that reads the
     * upload API.
     */
    @Test
    @Order(12)
    void askingForABuildWithAnythingButTheAdminRoleIsRejected() {
        String readerToken = fetchAccessToken(AUTH_BASE_URL, "jme-doc-reader", "secret");

        assertThat(statusOfPosting(BUILDS_PATH, uploadToken())).isEqualTo(403);
        assertThat(statusOfPosting(BUILDS_PATH, readerToken)).isEqualTo(403);
        assertThat(statusOfPosting(SHELL_BUILDS_PATH, uploadToken())).isEqualTo(403);
        assertThat(statusOfPosting(SHELL_BUILDS_PATH, readerToken)).isEqualTo(403);
    }

    /**
     * And the other way round: the roles that administer a site do not let their holder change the documentation
     * of a system. The two resources are separate in both directions.
     */
    @Test
    @Order(13)
    void uploadingWithTheOperatorRoleIsRejected() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .contentType("application/zip")
                .queryParams(DocumentationSets.parameters())
                .body(DocumentationSets.bundle())
                .when()
                .put(UPLOAD_PATH + UUID.randomUUID())
                .then()
                .statusCode(403);
    }

    @Test
    @Order(14)
    void readingTheStateOfTheSiteWithAnUploadRoleIsRejected() {
        for (String path : List.of(SITE_PATH, BUILDS_PATH, PARTS_PATH, SHELL_BUILDS_PATH)) {
            given().baseUri(DOC_BASE_URL)
                    .auth().oauth2(uploadToken())
                    .when()
                    .get(path)
                    .then()
                    .statusCode(403);
        }
    }

    @Test
    @Order(15)
    void administeringASiteWithoutATokenIsRejected() {
        for (String path : List.of(SITE_PATH, BUILDS_PATH, PARTS_PATH, SHELL_BUILDS_PATH)) {
            given().baseUri(DOC_BASE_URL).when().get(path).then().statusCode(401);
        }
        given().baseUri(DOC_BASE_URL).when().post(BUILDS_PATH).then().statusCode(401);
        given().baseUri(DOC_BASE_URL).when().post(SHELL_BUILDS_PATH).then().statusCode(401);
    }

    /**
     * A site is configuration, so a site this instance does not configure is a typo in the request rather than
     * something that might appear later - and it is refused rather than answered with an empty history.
     */
    @Test
    @Order(16)
    void askingForABuildOfASiteThisInstanceDoesNotConfigureIsNotFound() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post("/api/sites/governance/builds")
                .then()
                .statusCode(404);
    }

    /**
     * Waits for the build one of this suite's asks led to, and answers its id. It has to be a newer build than
     * what stood before, so that a run left over from an earlier suite - or from an earlier run against the same
     * containers, which keep their data while they are left running - can never be mistaken for the one just
     * asked for.
     */
    private long awaitSucceededBuildAfter(long previousNewestBuildId, String trigger) {
        String succeededBuildsOfThatTrigger =
                "findAll { it.state == 'SUCCEEDED' && it.trigger == '%s' }.id".formatted(trigger);
        return await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> history().getList(succeededBuildsOfThatTrigger, Long.class).stream()
                        .filter(id -> id > previousNewestBuildId)
                        .max(Comparator.naturalOrder())
                        .orElse(null), Objects::nonNull);
    }

    /** The newest build of the site, or zero when it has never been built - the ids come from a sequence. */
    private long newestBuildId() {
        return buildIds().stream().mapToLong(Long::longValue).max().orElse(0);
    }

    private List<Long> buildIds() {
        return history().getList("id", Long.class);
    }

    /** The build history of every part of the site, newest first, read with the role that may read it. */
    private JsonPath history() {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .queryParam("limit", 100)
                .when()
                .get(BUILDS_PATH)
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
    }

    private JsonPath readJson(String path) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(path)
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
    }

    private int statusOfPosting(String path, String accessToken) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(accessToken)
                .when()
                .post(path)
                .then()
                .extract()
                .statusCode();
    }

    private String uploadToken() {
        return fetchAccessToken(AUTH_BASE_URL, "jme-doc-pipeline", "secret");
    }

    private String operatorToken() {
        return fetchAccessToken(AUTH_BASE_URL, "jme-doc-operator", "secret");
    }

    /**
     * A client for the object storage of the example. Path style addressing, because the bucket of a local
     * S3-compatible storage is a path and not a subdomain.
     */
    private S3Client objectStorage() {
        return S3Client.builder()
                .endpointOverride(objectStorageEndpoint)
                .region(Region.of(objectStorageRegion))
                .credentialsProvider(StaticCredentialsProvider.create(
                        AwsBasicCredentials.create(objectStorageAccessKey, objectStorageSecretKey)))
                .forcePathStyle(true)
                .build();
    }
}
