package ch.admin.bit.jeap.jme.doc;

import ch.admin.bit.jeap.jme.test.BootServiceSpringIntegrationTestBase;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Value;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectTaggingRequest;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
import software.amazon.awssdk.services.s3.model.S3Object;
import software.amazon.awssdk.services.s3.model.Tag;

import java.net.URI;
import java.time.Duration;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.endsWith;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.nullValue;

/**
 * Generates the documentation site of this example and reads what the generator did, with tokens of the OAuth
 * mock server.
 * <p>
 * This is the half of the doc service that publishes rather than receives, and it is what makes the example need
 * Node: the site is generated by running the site generator as a child process. So this is the suite that fails
 * when the local development environment is not set up - if the doc service never becomes ready here, its
 * {@code jeap.doc.build.*} configuration is where to look, and {@code docs/local-development.md} says what it
 * has to point at.
 * <p>
 * Two rules an operator has to know are shown. <b>Asking is not building</b>: the endpoint leaves a request that
 * an instance picks up on its next poll, and answers how long that takes at most. And <b>administering a site is
 * not a system's own business</b>: the upload roles carry the system in their tenant part so that a pipeline can
 * only change its own documentation, while a build regenerates the whole site with the documentation of every
 * system on it - so it is granted on a resource of its own that no pipeline holds.
 * <p>
 * The tests are ordered because they are one story: an upload asks for a build, an operator asks for one and the
 * site is published, and everything after that reads what those two left behind. That several triggers collapse
 * into a single build is not asserted here - that is the doc service's own behaviour and is covered there. This
 * suite is about the instance being wired up correctly.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class DocSiteExampleIT extends BootServiceSpringIntegrationTestBase {

    private static final List<Integer> SERVICE_PORTS = reserveFreePorts(2);
    private static final int AUTH_PORT = SERVICE_PORTS.getFirst();
    private static final int DOC_PORT = SERVICE_PORTS.get(1);
    private static final String AUTH_BASE_URL = "http://localhost:" + AUTH_PORT + "/jme-doc-auth-scs";
    private static final String DOC_BASE_URL = "http://localhost:" + DOC_PORT + "/jme-doc-service";

    /**
     * The only site this example configures. It is served at the context root, and it is the site an upload that
     * names none belongs to.
     */
    private static final String SITE = "default";

    private static final String SITE_PATH = "/api/sites/" + SITE;
    private static final String BUILDS_PATH = SITE_PATH + "/builds";
    private static final String UPLOAD_PATH = "/api/uploads/docs/";

    /** What the site of this example calls itself - configured in the instance, and read back off the page. */
    private static final String SITE_TITLE = "JME Documentation";

    /**
     * How often the instance under test looks whether a build has been asked for. Far below the 30 seconds of a
     * real instance, because every test here waits for a build: it is the one number that decides how long this
     * suite takes, and the endpoint answers it as {@code picksUpWithinSeconds}, which is asserted below.
     */
    private static final int POLL_INTERVAL_SECONDS = 2;

    /**
     * How long a build may take before the suite gives up on it. Generously above the ten to twenty seconds the
     * site generator needs, because the first run on a cold machine has a bundler to warm up.
     */
    private static final Duration BUILD_TIMEOUT = Duration.ofMinutes(5);

    /**
     * The tag every file of a generated site carries, and what the second lifecycle rule of the bucket selects
     * on - see docker/docker-compose.yml. The bundle of an upload carries the same key with the value
     * {@code upload}, which is what keeps one rule from expiring the other's objects.
     */
    private static final String SITE_TAG_KEY = "jeap-doc-content";
    private static final String SITE_TAG_VALUE = "site";

    /** The build this suite published, so that everything read afterwards is read about that build and no other. */
    private static long publishedBuildId;

    @Value("${jme-doc-test.objectstorage.endpoint-url}")
    private URI objectStorageEndpoint;
    @Value("${jme-doc-test.objectstorage.region}")
    private String objectStorageRegion;
    @Value("${jme-doc-test.objectstorage.access-key}")
    private String objectStorageAccessKey;
    @Value("${jme-doc-test.objectstorage.secret-key}")
    private String objectStorageSecretKey;
    @Value("${jme-doc-test.objectstorage.bucket}")
    private String documentationBucket;

    /**
     * Three settings of the doc service are the suite's rather than the instance's, and each one is here to make
     * an outcome of this suite the outcome of something it did:
     * <ul>
     *   <li>the poll interval, so a build starts seconds after it is asked for instead of within half a minute;
     *   <li>no publication schedule, so the only builds that happen are the ones these tests ask for;
     *   <li>the publication URL, which names the origin in the metadata of the generated pages - and the service
     *       runs on a free port here rather than on the 8080 the instance configures.
     * </ul>
     * Everything else - where Node is, where the site template's dependencies are, what the site is called - is
     * the instance's own configuration, which is what this suite is here to exercise.
     */
    @BeforeAll
    static void startServices() throws Exception {
        startService("jme-doc-auth-scs", AUTH_BASE_URL, Map.of(
                "server.port", String.valueOf(AUTH_PORT),
                "mockserver.base-url", AUTH_BASE_URL));
        startService("jme-doc-service", DOC_BASE_URL, Map.of(
                "server.port", String.valueOf(DOC_PORT),
                "jeap.security.oauth2.resourceserver.authorization-server.issuer", AUTH_BASE_URL,
                "jeap.security.oauth2.resourceserver.authorization-server.jwk-set-uri",
                AUTH_BASE_URL + "/.well-known/jwks.json",
                "jeap.doc.build.poll-interval", "PT" + POLL_INTERVAL_SECONDS + "S",
                "jeap.doc.sites." + SITE + ".publication-schedule", "",
                "jeap.doc.publication.url", "http://localhost:" + DOC_PORT));
    }

    /**
     * The other half of what an upload does. The pipeline asks for nothing but the upload; the site it uploaded
     * to is published because it is configured to be published on upload - which is the default, and is what
     * makes documentation appear without anybody operating anything.
     */
    @Test
    @Order(1)
    void anUploadAsksForABuildOfTheSiteItBelongsTo() {
        long before = newestBuildId();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(uploadToken())
                .contentType("application/zip")
                .queryParams(DocumentationSets.parameters())
                .body(DocumentationSets.bundle())
                .when()
                .put(UPLOAD_PATH + UUID.randomUUID())
                .then()
                .statusCode(201);

        awaitSucceededBuildAfter(before, "UPLOAD");
    }

    /**
     * Asking is not building: the answer is a 202 saying that the request stands and how long it takes at most
     * until an instance claims it, and the build then happens on that instance rather than on the request thread.
     */
    @Test
    @Order(2)
    void askingForABuildPublishesTheSite() {
        long before = newestBuildId();

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post(BUILDS_PATH)
                .then()
                .statusCode(202)
                .body("site", equalTo(SITE))
                .body("requested", equalTo(true))
                .body("trigger", equalTo("MANUAL"))
                .body("pendingSince", notNullValue())
                .body("picksUpWithinSeconds", equalTo(POLL_INTERVAL_SECONDS));

        publishedBuildId = awaitSucceededBuildAfter(before, "MANUAL");

        JsonPath status = readJson(SITE_PATH);
        assertThat(status.getString("site")).isEqualTo(SITE);
        assertThat(status.getString("title")).isEqualTo(SITE_TITLE);
        assertThat(status.getList("environments", String.class)).containsExactly("dev", "ref", "abn", "prod");
        assertThat(status.getBoolean("publishOnUpload")).isTrue();
        assertThat(status.getLong("published.id")).isEqualTo(publishedBuildId);
    }

    /**
     * The documentation is served to anyone who can reach the service, and the API is not - which is the whole of
     * that decision, seen from outside. What the page says comes from the instance: the title is the one
     * configured in its application.yml, and the root of the site is its main environment.
     */
    @Test
    @Order(3)
    void theSiteIsServedToAnyoneWithoutAToken() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/")
                .then()
                .statusCode(200)
                .body(containsString(SITE_TITLE))
                .body(containsString("Production"));
    }

    /**
     * Every environment of the site is a tree of its own below it, and the main one is additionally served at the
     * root. The site is generated with a trailing slash on every route, so the form without one is a redirect
     * rather than a second URL for the same page.
     */
    @Test
    @Order(4)
    void everyEnvironmentIsServedUnderItsOwnPath() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/dev/")
                .then()
                .statusCode(200)
                .body(containsString("Development"));

        given().baseUri(DOC_BASE_URL)
                .redirects().follow(false)
                .when()
                .get("/dev")
                .then()
                .statusCode(301)
                .header("Location", endsWith("/dev/"));
    }

    /**
     * The site brings its own not-found page, and it is served with the status that says so - a reader gets the
     * navigation of the documentation they were looking for rather than an error page of the service.
     */
    @Test
    @Order(5)
    void anUnknownPageIsAnsweredWithTheSitesOwnNotFoundPage() {
        given().baseUri(DOC_BASE_URL)
                .when()
                .get("/nothing-was-published-here/")
                .then()
                .statusCode(404)
                .body(containsString("Page Not Found"));
    }

    /**
     * What the generator has been doing, which is the answer to <i>why is this site not updating</i> without
     * reading a log: every run with its trigger, its state, what it produced, and how much of the run was the
     * site generator itself.
     */
    @Test
    @Order(6)
    void theHistorySaysWhatTheGeneratorDid() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(BUILDS_PATH + "/" + publishedBuildId)
                .then()
                .statusCode(200)
                .body("trigger", equalTo("MANUAL"))
                .body("state", equalTo("SUCCEEDED"))
                .body("startedAt", notNullValue())
                .body("finishedAt", notNullValue())
                .body("instance", notNullValue())
                .body("objectPrefix", equalTo(SITE + "/" + publishedBuildId))
                .body("pageCount", greaterThan(0))
                .body("sizeInBytes", greaterThan(0))
                .body("docusaurusMillis", greaterThan(0))
                .body("failureReason", nullValue());

        assertThat(buildIds()).isSortedAccordingTo(Comparator.reverseOrder()).contains(publishedBuildId);
    }

    /**
     * Where a generated site ends up: under the prefix the build record names, below the site prefix of the
     * instance, and tagged - so that the lifecycle rule of the bucket expires the sites nobody serves any more
     * without touching the bundles of the uploads, which carry the same tag key with a different value.
     */
    @Test
    @Order(7)
    void theGeneratedSiteLiesInTheObjectStorageUnderThePrefixOfItsBuild() {
        String prefix = "sites/" + SITE + "/" + publishedBuildId + "/";

        try (S3Client objectStorage = objectStorage()) {
            List<S3Object> published = objectStorage.listObjectsV2(ListObjectsV2Request.builder()
                    .bucket(documentationBucket).prefix(prefix).build()).contents();

            assertThat(published).isNotEmpty()
                    .extracting(S3Object::key)
                    .contains(prefix + "index.html", prefix + "dev/index.html");

            List<Tag> tags = objectStorage.getObjectTagging(GetObjectTaggingRequest.builder()
                    .bucket(documentationBucket).key(prefix + "index.html").build()).tagSet();
            assertThat(tags).extracting(Tag::key, Tag::value).containsExactly(tuple(SITE_TAG_KEY, SITE_TAG_VALUE));
        }
    }

    /**
     * A pipeline may not publish the site. Its role is granted per system in the tenant part precisely so that it
     * can only change its own system's documentation, and a build republishes the documentation of every system
     * on the site - so the upload role is not a lever over it, and neither is the role that reads the upload API.
     */
    @Test
    @Order(8)
    void askingForABuildWithAnythingButTheAdminRoleIsRejected() {
        assertThat(statusOfAskingForABuildWith(uploadToken())).isEqualTo(403);
        assertThat(statusOfAskingForABuildWith(fetchAccessToken(AUTH_BASE_URL, "jme-doc-reader", "secret")))
                .isEqualTo(403);
    }

    /**
     * And the other way round: the roles that administer a site do not let their holder change the documentation
     * of a system. The two resources are separate in both directions.
     */
    @Test
    @Order(9)
    void uploadingWithTheOperatorRoleIsRejected() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .contentType("application/zip")
                .queryParams(DocumentationSets.parameters())
                .body(DocumentationSets.bundle())
                .when()
                .put(UPLOAD_PATH + UUID.randomUUID())
                .then()
                .statusCode(403);
    }

    @Test
    @Order(10)
    void readingTheStateOfTheSiteWithAnUploadRoleIsRejected() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(uploadToken())
                .when()
                .get(SITE_PATH)
                .then()
                .statusCode(403);

        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(uploadToken())
                .when()
                .get(BUILDS_PATH)
                .then()
                .statusCode(403);
    }

    @Test
    @Order(11)
    void administeringASiteWithoutATokenIsRejected() {
        given().baseUri(DOC_BASE_URL).when().post(BUILDS_PATH).then().statusCode(401);
        given().baseUri(DOC_BASE_URL).when().get(SITE_PATH).then().statusCode(401);
        given().baseUri(DOC_BASE_URL).when().get(BUILDS_PATH).then().statusCode(401);
    }

    /**
     * A site is configuration, so a site this instance does not configure is a typo in the request rather than
     * something that might appear later - and it is refused rather than answered with an empty history.
     */
    @Test
    @Order(12)
    void askingForABuildOfASiteThisInstanceDoesNotConfigureIsNotFound() {
        given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .post("/api/sites/governance/builds")
                .then()
                .statusCode(404);
    }

    /**
     * Waits for the build one of this suite's triggers asked for, and answers its id. It has to be a newer build
     * than what stood before, so that a run left over from an earlier suite - or from an earlier run against the
     * same containers, which keep their data between runs - can never be mistaken for the one just asked for.
     */
    private long awaitSucceededBuildAfter(long previousNewestBuildId, String trigger) {
        String succeededBuildsOfThatTrigger =
                "findAll { it.state == 'SUCCEEDED' && it.trigger == '%s' }.id".formatted(trigger);
        return await().atMost(BUILD_TIMEOUT)
                .pollInterval(Duration.ofSeconds(1))
                .until(() -> history().getList(succeededBuildsOfThatTrigger, Long.class).stream()
                        .filter(id -> id > previousNewestBuildId)
                        .max(Comparator.naturalOrder())
                        .orElse(null), Objects::nonNull);
    }

    /** The newest build of the site, or zero when it has never been built - the ids come from a sequence. */
    private long newestBuildId() {
        return buildIds().stream().mapToLong(Long::longValue).max().orElse(0);
    }

    private List<Long> buildIds() {
        return history().getList("id", Long.class);
    }

    /** The build history, newest first, read with the role that may read it. */
    private JsonPath history() {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .queryParam("limit", 100)
                .when()
                .get(BUILDS_PATH)
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
    }

    private JsonPath readJson(String path) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(operatorToken())
                .when()
                .get(path)
                .then()
                .statusCode(200)
                .extract()
                .jsonPath();
    }

    private int statusOfAskingForABuildWith(String accessToken) {
        return given().baseUri(DOC_BASE_URL)
                .auth().oauth2(accessToken)
                .when()
                .post(BUILDS_PATH)
                .then()
                .extract()
                .statusCode();
    }

    private String uploadToken() {
        return fetchAccessToken(AUTH_BASE_URL, "jme-doc-pipeline", "secret");
    }

    private String operatorToken() {
        return fetchAccessToken(AUTH_BASE_URL, "jme-doc-operator", "secret");
    }

    /**
     * A client for the object storage of the example. Path style addressing, because the bucket of a local
     * S3-compatible storage is a path and not a subdomain.
     */
    private S3Client objectStorage() {
        return S3Client.builder()
                .endpointOverride(objectStorageEndpoint)
                .region(Region.of(objectStorageRegion))
                .credentialsProvider(StaticCredentialsProvider.create(
                        AwsBasicCredentials.create(objectStorageAccessKey, objectStorageSecretKey)))
                .forcePathStyle(true)
                .build();
    }
}
